In [2]:
%pwd

'/mnt/c/Users/kubar/Documents/Sem7/labelthissongforme/notebooks'

'/mnt/c/Users/kubar/Documents/Sem7/labelthissongforme/notebooks'

In [3]:
import numpy as np
import pandas as pd
import random
import torch
import os

from sklearn.model_selection import train_test_split

In [4]:
def set_seed(seed: int = 42) -> None:
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    # Set a fixed value for the hash seed
    os.environ["PYTHONHASHSEED"] = str(seed)
    print(f"Random seed set as {seed}")

set_seed(123456)

Random seed set as 123456


In [5]:
split_path = "../split/mtat-20/"
os.makedirs(split_path, exist_ok=True)
n_tags = 20

In [6]:
broken_tracks = [
    "6/norine_braun-now_and_zen-08-gently-117-146.mp3",
    "8/jacob_heringman-josquin_des_prez_lute_settings-19-gintzler__pater_noster-204-233.mp3",
    "9/american_baroque-dances_and_suites_of_rameau_and_couperin-25-le_petit_rien_xiveme_ordre_couperin-88-117.mp3",
    "c/domased-new_memories-07-first_sun_rays-233-262.mp3",
    "d/tim_rayborn-chordae-04-sempr_alegria-784-813.mp3"
]

In [7]:
adnotations = pd.read_csv('../data/mtat/annotations_final.csv', sep='\t', index_col="clip_id")
adnotations = adnotations[~adnotations["mp3_path"].isin(broken_tracks)]
adnotations

no voice  singer  duet  plucking  hard rock  world  bongos  \
clip_id                                                               
2               0       0     0         0          0      0       0   
6               0       0     0         0          0      0       0   
10              0       0     0         0          0      0       0   
11              0       0     0         0          0      0       0   
12              0       0     0         0          0      0       0   
...           ...     ...   ...       ...        ...    ...     ...   
58899           0       0     0         0          0      0       0   
58906           0       0     0         0          0      0       0   
58907           0       0     0         0          0      0       0   
58908           0       0     0         0          0      0       0   
58915           0       0     0         0          0      0       0   

         harpsichord  female singing  clasical  ...  rap  metal  hip hop  \
clip_id                                         ...                        
2                  0               0         0  ...    0      0        0   
6                  0               0         0  ...    0      0        0   
10                 0               0         0  ...    0      0        0   
11                 0               0         0  ...    0      0        0   
12                 0               0         0  ...    0      0        0   
...              ...             ...       ...  ...  ...    ...      ...   
58899              0               0         0  ...    0      0        0   
58906              0               0         0  ...    0      0        0   
58907              0               0         0  ...    0      0        0   
58908              0               0         0  ...    0      0        0   
58915              0               0         0  ...    0      0        0   

         quick  water  baroque  women  fiddle  english  \
clip_id                                                  
2            0      0        0      0       0        0   
6            0      0        1      0       0        0   
10           0      0        0      0       0        0   
11           0      0        0      0       0        0   
12           0      0        0      0       0        0   
...        ...    ...      ...    ...     ...      ...   
58899        0      0        0      0       0        0   
58906        0      0        0      0       0        0   
58907        0      0        0      0       0        0   
58908        0      0        0      0       0        0   
58915        0      0        0      0       0        0   

                                                  mp3_path  
clip_id                                                     
2        f/american_bach_soloists-j_s__bach_solo_cantat...  
6        f/american_bach_soloists-j_s__bach_solo_cantat...  
10       f/american_bach_soloists-j_s__bach_solo_cantat...  
11       f/american_bach_soloists-j_s__bach_solo_cantat...  
12       f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                    ...  
58899    8/jacob_heringman-blame_not_my_lute-56-la_bres...  
58906    8/jacob_heringman-blame_not_my_lute-57-lost_is...  
58907    8/jacob_heringman-blame_not_my_lute-57-lost_is...  
58908    8/jacob_heringman-blame_not_my_lute-57-lost_is...  
58915    8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[25858 rows x 189 columns]

In [8]:
clip_info = pd.read_csv('../data/mtat/clip_info_final.csv', sep='\t')
clip_info

clip_id  track_number                    title                  artist  \
0            2             1           BWV54 - I Aria  American Bach Soloists   
1            6             1           BWV54 - I Aria  American Bach Soloists   
2           10             1           BWV54 - I Aria  American Bach Soloists   
3           11             1           BWV54 - I Aria  American Bach Soloists   
4           12             1           BWV54 - I Aria  American Bach Soloists   
...        ...           ...                      ...                     ...   
31377    58899            56            La Bressanina         Jacob Heringman   
31378    58906            57       Lost is my Lyberty         Jacob Heringman   
31379    58907            57       Lost is my Lyberty         Jacob Heringman   
31380    58908            57       Lost is my Lyberty         Jacob Heringman   
31381    58915            58  A Toy for Monica Bishop         Jacob Heringman   

                         album  \
0      J.S. Bach Solo Cantatas   
1      J.S. Bach Solo Cantatas   
2      J.S. Bach Solo Cantatas   
3      J.S. Bach Solo Cantatas   
4      J.S. Bach Solo Cantatas   
...                        ...   
31377        Blame Not My Lute   
31378        Blame Not My Lute   
31379        Blame Not My Lute   
31380        Blame Not My Lute   
31381        Blame Not My Lute   

                                                     url  segmentStart  \
0      http://www.magnatune.com/artists/albums/abs-so...            30   
1      http://www.magnatune.com/artists/albums/abs-so...           146   
2      http://www.magnatune.com/artists/albums/abs-so...           262   
3      http://www.magnatune.com/artists/albums/abs-so...           291   
4      http://www.magnatune.com/artists/albums/abs-so...           320   
...                                                  ...           ...   
31377  http://www.magnatune.com/artists/albums/hering...            88   
31378  http://www.magnatune.com/artists/albums/hering...             0   
31379  http://www.magnatune.com/artists/albums/hering...            30   
31380  http://www.magnatune.com/artists/albums/hering...            59   
31381  http://www.magnatune.com/artists/albums/hering...             0   

       segmentEnd                                       original_url  \
0              59  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
1             175  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
2             291  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
3             320  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
4             349  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
...           ...                                                ...   
31377         117  http://he3.magnatune.com/all/56-La%20Bressanin...   
31378          29  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31379          59  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31380          88  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31381          29  http://he3.magnatune.com/all/58-A%20Toy%20for%...   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
31377  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
31378  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31379  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31380  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31381  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[31382 rows x 10 columns]

# n tags with the largest quantity in dataset

In [9]:
tags = adnotations.filter(regex='[^mp3_path]').sum().nlargest(n_tags)
tags

guitar        4851
classical     4269
slow          3547
techno        2953
strings       2726
drums         2598
electronic    2519
rock          2371
fast          2304
piano         2056
ambient       1956
beat          1906
violin        1826
vocal         1729
synth         1716
female        1474
indian        1395
opera         1296
male          1279
singing       1211
dtype: int64

In [10]:
tags = tags.keys().to_numpy('str')
np.save(open(os.path.join(split_path, 'tags.npy'), 'wb'), tags)
tags

array(['guitar', 'classical', 'slow', 'techno', 'strings', 'drums',
       'electronic', 'rock', 'fast', 'piano', 'ambient', 'beat', 'violin',
       'vocal', 'synth', 'female', 'indian', 'opera', 'male', 'singing'],
      dtype='<U10')

# Binary tags

In [11]:
binary = adnotations[tags]
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
clip_id                                                                      
2             0          1     0       0        1      0           0     0   
6             0          1     0       0        1      0           0     0   
10            0          1     0       0        0      0           0     0   
11            0          0     0       0        0      0           0     0   
12            0          1     0       0        1      0           0     0   
...         ...        ...   ...     ...      ...    ...         ...   ...   
58899         1          0     0       0        0      0           0     0   
58906         1          0     1       0        1      0           0     0   
58907         1          1     1       0        1      0           0     0   
58908         1          1     1       0        0      0           0     0   
58915         1          1     1       0        0      0           0     0   

         fast  piano  ambient  beat  violin  vocal  synth  female  indian  \
clip_id                                                                     
2           0      0        0     0       1      0      0       0       0   
6           0      0        0     0       1      0      0       0       0   
10          0      0        0     0       0      0      0       0       0   
11          0      0        0     0       0      0      0       0       0   
12          0      0        0     0       1      0      0       0       0   
...       ...    ...      ...   ...     ...    ...    ...     ...     ...   
58899       0      0        0     0       0      0      0       0       0   
58906       0      0        0     0       0      0      0       0       0   
58907       0      0        0     0       0      0      0       0       0   
58908       0      0        0     0       0      0      0       0       0   
58915       0      0        0     0       0      0      0       0       0   

         opera  male  singing  
clip_id                        
2            1     0        0  
6            1     0        0  
10           1     0        0  
11           1     0        0  
12           0     0        0  
...        ...   ...      ...  
58899        0     0        0  
58906        0     0        0  
58907        0     0        0  
58908        0     0        0  
58915        0     0        0  

[25858 rows x 20 columns]

In [12]:
indexes_to_keep = binary[binary.sum(axis=1) != 0].index.values
indexes_to_keep

array([    2,     6,    10, ..., 58907, 58908, 58915])

In [13]:
binary = binary[binary.index.isin(indexes_to_keep)]
binary.insert(0, "clip_id", binary.index)
binary

clip_id  guitar  classical  slow  techno  strings  drums  electronic  \
clip_id                                                                         
2              2       0          1     0       0        1      0           0   
6              6       0          1     0       0        1      0           0   
10            10       0          1     0       0        0      0           0   
11            11       0          0     0       0        0      0           0   
12            12       0          1     0       0        1      0           0   
...          ...     ...        ...   ...     ...      ...    ...         ...   
58899      58899       1          0     0       0        0      0           0   
58906      58906       1          0     1       0        1      0           0   
58907      58907       1          1     1       0        1      0           0   
58908      58908       1          1     1       0        0      0           0   
58915      58915       1          1     1       0        0      0           0   

         rock  fast  ...  ambient  beat  violin  vocal  synth  female  indian  \
clip_id              ...                                                        
2           0     0  ...        0     0       1      0      0       0       0   
6           0     0  ...        0     0       1      0      0       0       0   
10          0     0  ...        0     0       0      0      0       0       0   
11          0     0  ...        0     0       0      0      0       0       0   
12          0     0  ...        0     0       1      0      0       0       0   
...       ...   ...  ...      ...   ...     ...    ...    ...     ...     ...   
58899       0     0  ...        0     0       0      0      0       0       0   
58906       0     0  ...        0     0       0      0      0       0       0   
58907       0     0  ...        0     0       0      0      0       0       0   
58908       0     0  ...        0     0       0      0      0       0       0   
58915       0     0  ...        0     0       0      0      0       0       0   

         opera  male  singing  
clip_id                        
2            1     0        0  
6            1     0        0  
10           1     0        0  
11           1     0        0  
12           0     0        0  
...        ...   ...      ...  
58899        0     0        0  
58906        0     0        0  
58907        0     0        0  
58908        0     0        0  
58915        0     0        0  

[19718 rows x 21 columns]

In [14]:
binary_np = binary.to_numpy()
np.save(os.path.join(split_path, 'binary.npy'), binary_np)
binary_np

array([[    2,     0,     1, ...,     1,     0,     0],
       [    6,     0,     1, ...,     1,     0,     0],
       [   10,     0,     1, ...,     1,     0,     0],
       ...,
       [58907,     1,     1, ...,     0,     0,     0],
       [58908,     1,     1, ...,     0,     0,     0],
       [58915,     1,     1, ...,     0,     0,     0]])

In [15]:
adnotations = adnotations[adnotations.index.isin(indexes_to_keep)]
adnotations = adnotations['mp3_path']
adnotations

clip_id
2        f/american_bach_soloists-j_s__bach_solo_cantat...
6        f/american_bach_soloists-j_s__bach_solo_cantat...
10       f/american_bach_soloists-j_s__bach_solo_cantat...
11       f/american_bach_soloists-j_s__bach_solo_cantat...
12       f/american_bach_soloists-j_s__bach_solo_cantat...
                               ...                        
58899    8/jacob_heringman-blame_not_my_lute-56-la_bres...
58906    8/jacob_heringman-blame_not_my_lute-57-lost_is...
58907    8/jacob_heringman-blame_not_my_lute-57-lost_is...
58908    8/jacob_heringman-blame_not_my_lute-57-lost_is...
58915    8/jacob_heringman-blame_not_my_lute-58-a_toy_f...
Name: mp3_path, Length: 19718, dtype: object

# Spliting dataset to train, valid and test datasets

In [16]:
dataset = pd.DataFrame(adnotations, columns=['idx', 'mp3_path'])
dataset["idx"] = dataset.index
dataset

idx                                           mp3_path
clip_id                                                          
2            2  f/american_bach_soloists-j_s__bach_solo_cantat...
6            6  f/american_bach_soloists-j_s__bach_solo_cantat...
10          10  f/american_bach_soloists-j_s__bach_solo_cantat...
11          11  f/american_bach_soloists-j_s__bach_solo_cantat...
12          12  f/american_bach_soloists-j_s__bach_solo_cantat...
...        ...                                                ...
58899    58899  8/jacob_heringman-blame_not_my_lute-56-la_bres...
58906    58906  8/jacob_heringman-blame_not_my_lute-57-lost_is...
58907    58907  8/jacob_heringman-blame_not_my_lute-57-lost_is...
58908    58908  8/jacob_heringman-blame_not_my_lute-57-lost_is...
58915    58915  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...

[19718 rows x 2 columns]

In [17]:
dataset.to_numpy()

array([[2,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-30-59.mp3'],
       [6,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [10,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-262-291.mp3'],
       ...,
       [58907,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-30-59.mp3'],
       [58908,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-59-88.mp3'],
       [58915,
        '8/jacob_heringman-blame_not_my_lute-58-a_toy_for_monica_bishop-0-29.mp3']],
      dtype=object)

In [18]:
train_ratio = 0.75
valid_ratio = 0.15
test_ratio = 0.1

In [19]:
train, test = train_test_split(dataset, test_size=1 - train_ratio)
valid, test = train_test_split(test, test_size=test_ratio/(test_ratio + valid_ratio))

In [20]:
dataset_train = train.to_numpy()
np.save(open(os.path.join(split_path, 'train.npy'), 'wb'), dataset_train)
dataset_train

array([[6595,
        '6/dr_kuch-analog_disease-02-completly_mysticism-117-146.mp3'],
       [7400, 'd/tim_rayborn-chordae-02-fors_souvenir-59-88.mp3'],
       [11678,
        '4/magnatune-romantic_dinner_classical_compilation-03-asteria__vive_ma_dame-262-291.mp3'],
       ...,
       [10511,
        '5/human_response-survival-02-the_rainy_season-146-175.mp3'],
       [8986,
        '2/maryse_carlin-rameau__pieces_de_clavecin_en_concerts__forqueray_suites_4_and_5-02-premier_concert__la_livri_rameau-30-59.mp3'],
       [18180,
        'a/asteria-soyes_loyal-04-jatendray_tant_guillaume_dufay-30-59.mp3']],
      dtype=object)

In [21]:
dataset_valid = valid.to_numpy()
np.save(open(os.path.join(split_path, 'valid.npy'), 'wb'), dataset_valid)
dataset_valid

array([[17712, '1/jeff_wahl-guinevere-04-freedom-146-175.mp3'],
       [34917,
        '8/kourosh_zolani-peaceful_planet-08-butterflies-117-146.mp3'],
       [26644,
        'b/seismic_anamoly-dead_mans_hand-06-deep_blue_eee-59-88.mp3'],
       ...,
       [3046,
        '7/jeni_melia-the_last_of_old_england-01-o_waly_waly_trad-146-175.mp3'],
       [17116,
        'd/ambient_teknology-the_all_seeing_eye_project-04-confusion_says-0-29.mp3'],
       [34436,
        '1/jacob_heringman-holburns_passion-08-a_french_toy_cittern-0-29.mp3']],
      dtype=object)

In [22]:
dataset_test = test.to_numpy()
np.save(open(os.path.join(split_path, 'test.npy'), 'wb'), dataset_test)
dataset_test

array([[13782, '2/indidginus-seismic-03-master_of_masters-349-378.mp3'],
       [31415,
        '7/american_bach_soloists-j_s__bach__mass_in_b_minor_cd2-07-et_in_spiritum_sanctum_dominum-262-291.mp3'],
       [5814,
        '0/jeffrey_luck_lucas-what_we_whisper-01-you_knew_it_well-175-204.mp3'],
       ...,
       [47511, '0/apa_ya-apa_ya-12-african_wedding_song-146-175.mp3'],
       [35566,
        'f/kenji_williams-faces_of_epiphany-08-free_energy-88-117.mp3'],
       [30965, '3/jag-four_strings-07-country_romp-30-59.mp3']],
      dtype=object)