In [18]:
import numpy as np
import pandas as pd

In [19]:
broken_tracks = [
    "9/american_baroque-dances_and_suites_of_rameau_and_couperin-25-le_petit_rien_xiveme_ordre_couperin-88-117.mp3",
    "d/tim_rayborn-chordae-04-sempr_alegria-784-813.mp3",
    "6/norine_braun-now_and_zen-08-gently-117-146.mp3"
]

In [20]:
adnotations = pd.read_csv('../data/mtat/annotations_final.csv', sep='\t')
adnotations = adnotations[~adnotations["mp3_path"].isin(broken_tracks)]
adnotations

clip_id  no voice  singer  duet  plucking  hard rock  world  bongos  \
0            2         0       0     0         0          0      0       0   
1            6         0       0     0         0          0      0       0   
2           10         0       0     0         0          0      0       0   
3           11         0       0     0         0          0      0       0   
4           12         0       0     0         0          0      0       0   
...        ...       ...     ...   ...       ...        ...    ...     ...   
25858    58899         0       0     0         0          0      0       0   
25859    58906         0       0     0         0          0      0       0   
25860    58907         0       0     0         0          0      0       0   
25861    58908         0       0     0         0          0      0       0   
25862    58915         0       0     0         0          0      0       0   

       harpsichord  female singing  ...  rap  metal  hip hop  quick  water  \
0                0               0  ...    0      0        0      0      0   
1                0               0  ...    0      0        0      0      0   
2                0               0  ...    0      0        0      0      0   
3                0               0  ...    0      0        0      0      0   
4                0               0  ...    0      0        0      0      0   
...            ...             ...  ...  ...    ...      ...    ...    ...   
25858            0               0  ...    0      0        0      0      0   
25859            0               0  ...    0      0        0      0      0   
25860            0               0  ...    0      0        0      0      0   
25861            0               0  ...    0      0        0      0      0   
25862            0               0  ...    0      0        0      0      0   

       baroque  women  fiddle  english  \
0            0      0       0        0   
1            1      0       0        0   
2            0      0       0        0   
3            0      0       0        0   
4            0      0       0        0   
...        ...    ...     ...      ...   
25858        0      0       0        0   
25859        0      0       0        0   
25860        0      0       0        0   
25861        0      0       0        0   
25862        0      0       0        0   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[25861 rows x 190 columns]

In [21]:
clip_info = pd.read_csv('../data/mtat/clip_info_final.csv', sep='\t')
clip_info

clip_id  track_number                    title                  artist  \
0            2             1           BWV54 - I Aria  American Bach Soloists   
1            6             1           BWV54 - I Aria  American Bach Soloists   
2           10             1           BWV54 - I Aria  American Bach Soloists   
3           11             1           BWV54 - I Aria  American Bach Soloists   
4           12             1           BWV54 - I Aria  American Bach Soloists   
...        ...           ...                      ...                     ...   
31377    58899            56            La Bressanina         Jacob Heringman   
31378    58906            57       Lost is my Lyberty         Jacob Heringman   
31379    58907            57       Lost is my Lyberty         Jacob Heringman   
31380    58908            57       Lost is my Lyberty         Jacob Heringman   
31381    58915            58  A Toy for Monica Bishop         Jacob Heringman   

                         album  \
0      J.S. Bach Solo Cantatas   
1      J.S. Bach Solo Cantatas   
2      J.S. Bach Solo Cantatas   
3      J.S. Bach Solo Cantatas   
4      J.S. Bach Solo Cantatas   
...                        ...   
31377        Blame Not My Lute   
31378        Blame Not My Lute   
31379        Blame Not My Lute   
31380        Blame Not My Lute   
31381        Blame Not My Lute   

                                                     url  segmentStart  \
0      http://www.magnatune.com/artists/albums/abs-so...            30   
1      http://www.magnatune.com/artists/albums/abs-so...           146   
2      http://www.magnatune.com/artists/albums/abs-so...           262   
3      http://www.magnatune.com/artists/albums/abs-so...           291   
4      http://www.magnatune.com/artists/albums/abs-so...           320   
...                                                  ...           ...   
31377  http://www.magnatune.com/artists/albums/hering...            88   
31378  http://www.magnatune.com/artists/albums/hering...             0   
31379  http://www.magnatune.com/artists/albums/hering...            30   
31380  http://www.magnatune.com/artists/albums/hering...            59   
31381  http://www.magnatune.com/artists/albums/hering...             0   

       segmentEnd                                       original_url  \
0              59  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
1             175  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
2             291  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
3             320  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
4             349  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
...           ...                                                ...   
31377         117  http://he3.magnatune.com/all/56-La%20Bressanin...   
31378          29  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31379          59  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31380          88  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31381          29  http://he3.magnatune.com/all/58-A%20Toy%20for%...   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
31377  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
31378  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31379  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31380  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31381  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[31382 rows x 10 columns]

# 50 tags with the largest quantity in dataset

In [22]:
tags = adnotations.filter(regex='[^(clip_id|mp3_path)]').sum().nlargest(50).keys().to_numpy('str')
tags

array(['guitar', 'classical', 'slow', 'techno', 'strings', 'drums',
       'electronic', 'rock', 'fast', 'piano', 'ambient', 'beat', 'violin',
       'vocal', 'synth', 'female', 'indian', 'opera', 'male', 'singing',
       'vocals', 'no vocals', 'harpsichord', 'loud', 'quiet', 'flute',
       'woman', 'male vocal', 'no vocal', 'pop', 'soft', 'sitar', 'solo',
       'man', 'classic', 'choir', 'voice', 'new age', 'dance',
       'male voice', 'female vocal', 'beats', 'harp', 'cello', 'no voice',
       'weird', 'country', 'female voice', 'metal', 'choral'],
      dtype='<U12')

# Binary tags

In [23]:
binary = adnotations[tags]
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
0           0          1     0       0        1      0           0     0   
1           0          1     0       0        1      0           0     0   
2           0          1     0       0        0      0           0     0   
3           0          0     0       0        0      0           0     0   
4           0          1     0       0        1      0           0     0   
...       ...        ...   ...     ...      ...    ...         ...   ...   
25858       1          0     0       0        0      0           0     0   
25859       1          0     1       0        1      0           0     0   
25860       1          1     1       0        1      0           0     0   
25861       1          1     1       0        0      0           0     0   
25862       1          1     1       0        0      0           0     0   

       fast  piano  ...  female vocal  beats  harp  cello  no voice  weird  \
0         0      0  ...             0      0     0      0         0      0   
1         0      0  ...             0      0     0      0         0      0   
2         0      0  ...             0      0     0      0         0      0   
3         0      0  ...             0      0     0      0         0      0   
4         0      0  ...             0      0     0      0         0      0   
...     ...    ...  ...           ...    ...   ...    ...       ...    ...   
25858     0      0  ...             0      0     0      0         0      0   
25859     0      0  ...             0      0     1      0         0      0   
25860     0      0  ...             0      0     0      0         0      0   
25861     0      0  ...             0      0     0      0         0      0   
25862     0      0  ...             0      0     0      0         0      0   

       country  female voice  metal  choral  
0            0             0      0       0  
1            0             0      0       0  
2            0             0      0       0  
3            0             0      0       0  
4            0             0      0       0  
...        ...           ...    ...     ...  
25858        0             0      0       0  
25859        0             0      0       0  
25860        0             0      0       0  
25861        0             0      0       0  
25862        0             0      0       0  

[25861 rows x 50 columns]

In [24]:
binary_np = binary.to_numpy()
print(binary_np.shape)
binary_np

(25861, 50)


array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

# Spliting dataset to train, valid and test datasets

In [25]:
dataset = pd.DataFrame(adnotations.mp3_path, columns=['idx', 'mp3_path'])
dataset["idx"] = dataset.index
dataset

idx                                           mp3_path
0          0  f/american_bach_soloists-j_s__bach_solo_cantat...
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
2          2  f/american_bach_soloists-j_s__bach_solo_cantat...
3          3  f/american_bach_soloists-j_s__bach_solo_cantat...
4          4  f/american_bach_soloists-j_s__bach_solo_cantat...
...      ...                                                ...
25858  25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...
25859  25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25860  25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25861  25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25862  25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...

[25861 rows x 2 columns]

In [26]:
dataset.to_numpy()

array([[0,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-30-59.mp3'],
       [1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [2,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-262-291.mp3'],
       ...,
       [25860,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-30-59.mp3'],
       [25861,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-59-88.mp3'],
       [25862,
        '8/jacob_heringman-blame_not_my_lute-58-a_toy_for_monica_bishop-0-29.mp3']],
      dtype=object)

In [27]:
train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

In [28]:
## Train

In [29]:
train = dataset.sample(round(train_ratio*len(dataset.index)),random_state=10)
train

idx                                           mp3_path
19179  19179  b/altri_stromenti-uccellini-10-beatus_uccellin...
10497  10497  8/tim_rayborn-veils_of_light-05-kashik-204-233...
19701  19701  7/falik-elvolution-10-mediterranean_blue-262-2...
14273  14273  3/dj_cary-downtempo_chill-07-enertia_trancevis...
17786  17786  8/mercy_machine-in_your_bed__the_remixes-09-da...
...      ...                                                ...
4665    4665  1/vito_paternoster-cd1bach_cello_suites-02-sui...
15802  15802  6/norine_braun-crow-08-another_mans_fate-88-11...
18558  18558    1/solace-the_gathering_season-09-saaba-0-29.mp3
1903    1903  e/dac_crowell-within_this_space-01-running_dep...
10337  10337  5/domased-selection-05-highway_accident-204-23...

[20689 rows x 2 columns]

In [30]:
dataset_train = train.to_numpy()
np.save(open('../split/mtat/train.npy', 'wb'), dataset_train)
dataset_train

array([[19179,
        'b/altri_stromenti-uccellini-10-beatus_uccellini-30-59.mp3'],
       [10497, '8/tim_rayborn-veils_of_light-05-kashik-204-233.mp3'],
       [19701, '7/falik-elvolution-10-mediterranean_blue-262-291.mp3'],
       ...,
       [18558, '1/solace-the_gathering_season-09-saaba-0-29.mp3'],
       [1903,
        'e/dac_crowell-within_this_space-01-running_depth-581-610.mp3'],
       [10337, '5/domased-selection-05-highway_accident-204-233.mp3']],
      dtype=object)

In [31]:
mini_train = train.sample(len(train.index) // 10,random_state=10)
mini_train

idx                                           mp3_path
11776  11776  7/roots_of_rebellion-the_looking_glass-06-amne...
5835    5835  b/philharmonia_baroque-beethoven_symphonies_no...
6723    6723  0/williamson-a_few_things_to_hear_before_we_al...
5194    5194  9/american_bach_soloists-heinrich_schutz__musi...
20461  20461  6/shira_kammen-the_castle_of_the_holly_king-11...
...      ...                                                ...
3340    3340   d/tim_rayborn-chordae-02-fors_souvenir-59-88.mp3
20653  20653            6/norine_braun-crow-11-crow-175-204.mp3
2098    2098  1/tanya_tomkins_and_eric_zivian-beethoven_pian...
8875    8875  6/sand_craig_and_dornenburg-biber_violin_sonat...
6469    6469   7/falik-elvolution-03-new_falik_city-320-349.mp3

[2068 rows x 2 columns]

In [32]:
dataset_mini_train = mini_train.to_numpy()
np.save(open('../split/mtat-mini/train.npy', 'wb'), dataset_mini_train)
dataset_mini_train

array([[11776,
        '7/roots_of_rebellion-the_looking_glass-06-amnesia-88-117.mp3'],
       [5835,
        'b/philharmonia_baroque-beethoven_symphonies_no_3_eroica_and_no_8-03-eroica_3rd_and_4th-465-494.mp3'],
       [6723,
        '0/williamson-a_few_things_to_hear_before_we_all_blow_up-03-raining_at_the_crescent_house-146-175.mp3'],
       ...,
       [2098,
        '1/tanya_tomkins_and_eric_zivian-beethoven_piano_and_cello_works-01-sonata_in_g_minor_op__5_no__2_adagio___allegro-697-726.mp3'],
       [8875,
        '6/sand_craig_and_dornenburg-biber_violin_sonatas-04-richter_toccatina_and_capriccio_in_d_minor-30-59.mp3'],
       [6469, '7/falik-elvolution-03-new_falik_city-320-349.mp3']],
      dtype=object)

In [33]:
## Valid

In [34]:
valid = dataset.drop(train.index)
valid = valid.sample(round(valid_ratio*len(dataset.index)),random_state=10)
valid

idx                                           mp3_path
2693    2693  6/ralph_meulenbroeks-gambomania-02-arabesque_m...
18124  18124    1/tim_rayborn-ashek-09-khamsa_ashra-117-146.mp3
4323    4323      a/tilopa-by_the_way-02-red_fullmoon-30-59.mp3
4399    4399       3/sherefe-opium-02-ruske_le_mome-117-146.mp3
11437  11437  6/dr_kuch-analog_disease-05-the_persuaders_dub...
...      ...                                                ...
16686  16686  1/ambient_teknology-phoenix-08-on_the_floor-59...
2972    2972  2/indidginus-seismic-02-catatonic_convertor-59...
21795  21795  9/the_strap_ons-geeking_crime-12-drugs_sex_vio...
10723  10723  1/touchinggrace-the_reformation_sessions-05-ne...
17791  17791  8/mercy_machine-in_your_bed__the_remixes-09-da...

[2586 rows x 2 columns]

In [35]:
dataset_valid = valid.to_numpy()
np.save(open('../split/mtat/valid.npy', 'wb'), dataset_valid)
dataset_valid

array([[2693,
        '6/ralph_meulenbroeks-gambomania-02-arabesque_martin_marais-146-175.mp3'],
       [18124, '1/tim_rayborn-ashek-09-khamsa_ashra-117-146.mp3'],
       [4323, 'a/tilopa-by_the_way-02-red_fullmoon-30-59.mp3'],
       ...,
       [21795,
        '9/the_strap_ons-geeking_crime-12-drugs_sex_violence-0-29.mp3'],
       [10723,
        '1/touchinggrace-the_reformation_sessions-05-new_delhi_breakdown-0-29.mp3'],
       [17791,
        '8/mercy_machine-in_your_bed__the_remixes-09-damascus_black_pans_mix-291-320.mp3']],
      dtype=object)

In [36]:
mini_valid = valid.sample(len(valid.index) // 10,random_state=10)
mini_valid

idx                                           mp3_path
15768  15768  c/seismic_anamoly-ramifications-08-always_on_m...
6070    6070     7/aba_structure-epic-03-houseboats-262-291.mp3
1786    1786  5/sitar-first_congregational_church_concert-01...
15149  15149  4/tim_rayborn-the_path_beyond-07-sehtar_dastan...
9393    9393  e/jamie_janover_and_michael_masley-all_strings...
...      ...                                                ...
272      272  c/jay_kishor-the_payans_concert-01-bhimpalasi-...
11696  11696  b/philharmonia_baroque-beethoven_symphonies_no...
9425    9425  a/janine_johnson-chopin_recital-04-variations_...
12598  12598  4/american_bach_soloists-j_s__bach__mass_in_b_...
3995    3995  b/satori-journey_to_other_worlds-02-other_worl...

[258 rows x 2 columns]

In [37]:
dataset_mini_valid = mini_valid.to_numpy()
np.save(open('../split/mtat-mini/valid.npy', 'wb'), dataset_mini_valid)
dataset_mini_valid

array([[15768,
        'c/seismic_anamoly-ramifications-08-always_on_my_mind-204-233.mp3'],
       [6070, '7/aba_structure-epic-03-houseboats-262-291.mp3'],
       [1786,
        '5/sitar-first_congregational_church_concert-01-raga_patdeep__alap__jay_kishor-465-494.mp3'],
       [15149,
        '4/tim_rayborn-the_path_beyond-07-sehtar_dastan-88-117.mp3'],
       [9393,
        'e/jamie_janover_and_michael_masley-all_strings_considered-04-under_fire_and_water-30-59.mp3'],
       [22370,
        'd/magnatune_compilation-new_age_and_jazz-12-trip_wamsley_finally-175-204.mp3'],
       [10427,
        'c/glen_bledsoe-up_and_down-05-invention_no__3-88-117.mp3'],
       [16412,
        '2/magnatune_compilation-electronica-08-joram_solipsism-204-233.mp3'],
       [24333,
        '6/ralph_meulenbroeks-gambomania-17-now_i_come_tobias_hume-30-59.mp3'],
       [10272, 'a/tilopa-pictures_of_silence-05-go-0-29.mp3'],
       [5253,
        'c/atomic_opera-alpha_and_oranges-03-all_these_things-233-262.

In [38]:
test = dataset.drop(train.index)
test = test.drop(valid.index)
test

idx                                           mp3_path
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
11        11  e/steven_devine-portrait_of_an_english_harpsic...
18        18  9/american_bach_soloists-heinrich_schutz__musi...
26        26  9/american_bach_soloists-heinrich_schutz__musi...
33        33  9/american_bach_soloists-heinrich_schutz__musi...
...      ...                                                ...
25796  25796  c/edward_martin-art_of_the_lute_in_renaissance...
25801  25801  1/richard_savino-murcia__danza_y_diferencias-3...
25835  25835  3/musica_franca-boismortier__sonatas_for_two_b...
25845  25845  8/jacob_heringman-blame_not_my_lute-49-grene_s...
25851  25851  7/magnaloops-world_loops_2-54-osdmichaelmasley...

[2586 rows x 2 columns]

In [39]:
dataset_test = test.to_numpy()
np.save(open('../split/mtat/test.npy', 'wb'), dataset_test)
dataset_test

array([[1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [11,
        'e/steven_devine-portrait_of_an_english_harpsichord-01-lesson_1_in_g_major_prelude_james_nares-0-29.mp3'],
       [18,
        '9/american_bach_soloists-heinrich_schutz__musicalische_exequien-01-musicalische_exequien_swv_279_teil_i_concert_in_form_einer_teutschen_begrabnismissa-146-175.mp3'],
       ...,
       [25835,
        '3/musica_franca-boismortier__sonatas_for_two_bassoons_and_continuo-38-chaconne_in_a_major_op__66-30-59.mp3'],
       [25845,
        '8/jacob_heringman-blame_not_my_lute-49-grene_sleves-0-29.mp3'],
       [25851,
        '7/magnaloops-world_loops_2-54-osdmichaelmasley644-0-29.mp3']],
      dtype=object)

In [40]:
mini_test = test.sample(len(test.index) // 10,random_state=10)
mini_test

idx                                           mp3_path
6392    6392  b/magnatune_compilation-world_fusion-03-michae...
16593  16593  5/arthur_yoria-of_the_lovely-08-my_best_routin...
23874  23874         a/kitka-nectar-15-predite_prelye-30-59.mp3
10799  10799  2/indidginus-as_above_so_below-05-omega_3-233-...
23844  23844  f/paul_berget-sl_weiss_on_11_strings-15-partit...
...      ...                                                ...
7601    7601  b/lisa_debenedictis-mixter_one-04-belowdufirst...
2297    2297    2/indidginus-seismic-01-superstring-378-407.mp3
2009    2009  5/kammen___swan-wild_wood-01-shetland_set-59-8...
5667    5667  5/john_fleagle-worlds_bliss__medieval_songs_of...
14541  14541     e/solace-balance-07-indigo_dragonfly-30-59.mp3

[258 rows x 2 columns]

In [41]:
dataset_mini_test = mini_test.to_numpy()
np.save(open('../split/mtat-mini/test.npy', 'wb'), dataset_mini_test)
dataset_mini_test

array([[6392,
        'b/magnatune_compilation-world_fusion-03-michael_masley_kubricks_tube-0-29.mp3'],
       [16593,
        '5/arthur_yoria-of_the_lovely-08-my_best_routines-88-117.mp3'],
       [23874, 'a/kitka-nectar-15-predite_prelye-30-59.mp3'],
       [10799, '2/indidginus-as_above_so_below-05-omega_3-233-262.mp3'],
       [23844,
        'f/paul_berget-sl_weiss_on_11_strings-15-partita_in_g_allemande-0-29.mp3'],
       [21026, '2/saros-soundscapes-11-natures_grace-349-378.mp3'],
       [19265,
        'f/american_baroque-the_four_seasons_by_vivaldi-10-concerto_no_4_in_g_minor_rv_297_winter__allegro_non_molto-59-88.mp3'],
       [6109,
        '6/farallon_recorder_quartet-ludwig_senfl-03-ich_weiss_nit_was_er_ihr_verbiess-0-29.mp3'],
       [3698, '4/human_response-delirious-02-landlocked-117-146.mp3'],
       [25125, '3/jag-four_strings-21-argenta_train_blues-146-175.mp3'],
       [3753, 'a/kitka-nectar-02-malo_selo_bulgaria-59-88.mp3'],
       [15975,
        'f/three_holies_c