In [2]:
import numpy as np
import pandas as pd

In [3]:
broken_tracks = [
    "9/american_baroque-dances_and_suites_of_rameau_and_couperin-25-le_petit_rien_xiveme_ordre_couperin-88-117.mp3",
    "d/tim_rayborn-chordae-04-sempr_alegria-784-813.mp3",
    "6/norine_braun-now_and_zen-08-gently-117-146.mp3"
]

In [4]:
adnotations = pd.read_csv('../data/mtat/annotations_final.csv', sep='\t')
adnotations = adnotations[~adnotations["mp3_path"].isin(broken_tracks)]
adnotations

clip_id  no voice  singer  duet  plucking  hard rock  world  bongos  \
0            2         0       0     0         0          0      0       0   
1            6         0       0     0         0          0      0       0   
2           10         0       0     0         0          0      0       0   
3           11         0       0     0         0          0      0       0   
4           12         0       0     0         0          0      0       0   
...        ...       ...     ...   ...       ...        ...    ...     ...   
25858    58899         0       0     0         0          0      0       0   
25859    58906         0       0     0         0          0      0       0   
25860    58907         0       0     0         0          0      0       0   
25861    58908         0       0     0         0          0      0       0   
25862    58915         0       0     0         0          0      0       0   

       harpsichord  female singing  ...  rap  metal  hip hop  quick  water  \
0                0               0  ...    0      0        0      0      0   
1                0               0  ...    0      0        0      0      0   
2                0               0  ...    0      0        0      0      0   
3                0               0  ...    0      0        0      0      0   
4                0               0  ...    0      0        0      0      0   
...            ...             ...  ...  ...    ...      ...    ...    ...   
25858            0               0  ...    0      0        0      0      0   
25859            0               0  ...    0      0        0      0      0   
25860            0               0  ...    0      0        0      0      0   
25861            0               0  ...    0      0        0      0      0   
25862            0               0  ...    0      0        0      0      0   

       baroque  women  fiddle  english  \
0            0      0       0        0   
1            1      0       0        0   
2            0      0       0        0   
3            0      0       0        0   
4            0      0       0        0   
...        ...    ...     ...      ...   
25858        0      0       0        0   
25859        0      0       0        0   
25860        0      0       0        0   
25861        0      0       0        0   
25862        0      0       0        0   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[25860 rows x 190 columns]

In [5]:
clip_info = pd.read_csv('../data/mtat/clip_info_final.csv', sep='\t')
clip_info

clip_id  track_number                    title                  artist  \
0            2             1           BWV54 - I Aria  American Bach Soloists   
1            6             1           BWV54 - I Aria  American Bach Soloists   
2           10             1           BWV54 - I Aria  American Bach Soloists   
3           11             1           BWV54 - I Aria  American Bach Soloists   
4           12             1           BWV54 - I Aria  American Bach Soloists   
...        ...           ...                      ...                     ...   
31377    58899            56            La Bressanina         Jacob Heringman   
31378    58906            57       Lost is my Lyberty         Jacob Heringman   
31379    58907            57       Lost is my Lyberty         Jacob Heringman   
31380    58908            57       Lost is my Lyberty         Jacob Heringman   
31381    58915            58  A Toy for Monica Bishop         Jacob Heringman   

                         album  \
0      J.S. Bach Solo Cantatas   
1      J.S. Bach Solo Cantatas   
2      J.S. Bach Solo Cantatas   
3      J.S. Bach Solo Cantatas   
4      J.S. Bach Solo Cantatas   
...                        ...   
31377        Blame Not My Lute   
31378        Blame Not My Lute   
31379        Blame Not My Lute   
31380        Blame Not My Lute   
31381        Blame Not My Lute   

                                                     url  segmentStart  \
0      http://www.magnatune.com/artists/albums/abs-so...            30   
1      http://www.magnatune.com/artists/albums/abs-so...           146   
2      http://www.magnatune.com/artists/albums/abs-so...           262   
3      http://www.magnatune.com/artists/albums/abs-so...           291   
4      http://www.magnatune.com/artists/albums/abs-so...           320   
...                                                  ...           ...   
31377  http://www.magnatune.com/artists/albums/hering...            88   
31378  http://www.magnatune.com/artists/albums/hering...             0   
31379  http://www.magnatune.com/artists/albums/hering...            30   
31380  http://www.magnatune.com/artists/albums/hering...            59   
31381  http://www.magnatune.com/artists/albums/hering...             0   

       segmentEnd                                       original_url  \
0              59  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
1             175  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
2             291  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
3             320  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
4             349  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
...           ...                                                ...   
31377         117  http://he3.magnatune.com/all/56-La%20Bressanin...   
31378          29  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31379          59  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31380          88  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31381          29  http://he3.magnatune.com/all/58-A%20Toy%20for%...   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
31377  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
31378  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31379  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31380  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31381  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[31382 rows x 10 columns]

# 50 tags with the largest quantity in dataset

In [6]:
tags = adnotations.filter(regex='[^(clip_id|mp3_path)]').sum().nlargest(50).keys().to_numpy('str')
tags

array(['guitar', 'classical', 'slow', 'techno', 'strings', 'drums',
       'electronic', 'rock', 'fast', 'piano', 'ambient', 'beat', 'violin',
       'vocal', 'synth', 'female', 'indian', 'opera', 'male', 'singing',
       'vocals', 'no vocals', 'harpsichord', 'loud', 'quiet', 'flute',
       'woman', 'male vocal', 'no vocal', 'pop', 'soft', 'sitar', 'solo',
       'man', 'classic', 'choir', 'voice', 'new age', 'dance',
       'male voice', 'female vocal', 'beats', 'harp', 'cello', 'no voice',
       'weird', 'country', 'female voice', 'metal', 'choral'],
      dtype='<U12')

# Binary tags

In [7]:
binary = adnotations[tags]
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
0           0          1     0       0        1      0           0     0   
1           0          1     0       0        1      0           0     0   
2           0          1     0       0        0      0           0     0   
3           0          0     0       0        0      0           0     0   
4           0          1     0       0        1      0           0     0   
...       ...        ...   ...     ...      ...    ...         ...   ...   
25858       1          0     0       0        0      0           0     0   
25859       1          0     1       0        1      0           0     0   
25860       1          1     1       0        1      0           0     0   
25861       1          1     1       0        0      0           0     0   
25862       1          1     1       0        0      0           0     0   

       fast  piano  ...  female vocal  beats  harp  cello  no voice  weird  \
0         0      0  ...             0      0     0      0         0      0   
1         0      0  ...             0      0     0      0         0      0   
2         0      0  ...             0      0     0      0         0      0   
3         0      0  ...             0      0     0      0         0      0   
4         0      0  ...             0      0     0      0         0      0   
...     ...    ...  ...           ...    ...   ...    ...       ...    ...   
25858     0      0  ...             0      0     0      0         0      0   
25859     0      0  ...             0      0     1      0         0      0   
25860     0      0  ...             0      0     0      0         0      0   
25861     0      0  ...             0      0     0      0         0      0   
25862     0      0  ...             0      0     0      0         0      0   

       country  female voice  metal  choral  
0            0             0      0       0  
1            0             0      0       0  
2            0             0      0       0  
3            0             0      0       0  
4            0             0      0       0  
...        ...           ...    ...     ...  
25858        0             0      0       0  
25859        0             0      0       0  
25860        0             0      0       0  
25861        0             0      0       0  
25862        0             0      0       0  

[25860 rows x 50 columns]

In [8]:
indexes_to_keep = binary[binary.sum(axis=1) != 0].index.values
binary = binary[binary.index.isin(indexes_to_keep)]
adnotations = adnotations[adnotations.index.isin(indexes_to_keep)]
binary.reset_index()
adnotations.reset_index()
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
0           0          1     0       0        1      0           0     0   
1           0          1     0       0        1      0           0     0   
2           0          1     0       0        0      0           0     0   
3           0          0     0       0        0      0           0     0   
4           0          1     0       0        1      0           0     0   
...       ...        ...   ...     ...      ...    ...         ...   ...   
25858       1          0     0       0        0      0           0     0   
25859       1          0     1       0        1      0           0     0   
25860       1          1     1       0        1      0           0     0   
25861       1          1     1       0        0      0           0     0   
25862       1          1     1       0        0      0           0     0   

       fast  piano  ...  female vocal  beats  harp  cello  no voice  weird  \
0         0      0  ...             0      0     0      0         0      0   
1         0      0  ...             0      0     0      0         0      0   
2         0      0  ...             0      0     0      0         0      0   
3         0      0  ...             0      0     0      0         0      0   
4         0      0  ...             0      0     0      0         0      0   
...     ...    ...  ...           ...    ...   ...    ...       ...    ...   
25858     0      0  ...             0      0     0      0         0      0   
25859     0      0  ...             0      0     1      0         0      0   
25860     0      0  ...             0      0     0      0         0      0   
25861     0      0  ...             0      0     0      0         0      0   
25862     0      0  ...             0      0     0      0         0      0   

       country  female voice  metal  choral  
0            0             0      0       0  
1            0             0      0       0  
2            0             0      0       0  
3            0             0      0       0  
4            0             0      0       0  
...        ...           ...    ...     ...  
25858        0             0      0       0  
25859        0             0      0       0  
25860        0             0      0       0  
25861        0             0      0       0  
25862        0             0      0       0  

[21108 rows x 50 columns]

In [9]:
binary[binary.sum(axis=1) != 0].index

Int64Index([    0,     1,     2,     3,     4,     5,     7,     8,    10,
               11,
            ...
            25853, 25854, 25855, 25856, 25857, 25858, 25859, 25860, 25861,
            25862],
           dtype='int64', length=21108)

In [10]:
binary_np = binary.to_numpy()
print(binary_np.shape)
binary_np

(21108, 50)


array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

# Spliting dataset to train, valid and test datasets

In [11]:
dataset = pd.DataFrame(adnotations.mp3_path, columns=['idx', 'mp3_path'])
dataset["idx"] = dataset.index
dataset

idx                                           mp3_path
0          0  f/american_bach_soloists-j_s__bach_solo_cantat...
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
2          2  f/american_bach_soloists-j_s__bach_solo_cantat...
3          3  f/american_bach_soloists-j_s__bach_solo_cantat...
4          4  f/american_bach_soloists-j_s__bach_solo_cantat...
...      ...                                                ...
25858  25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...
25859  25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25860  25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25861  25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25862  25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...

[21108 rows x 2 columns]

In [12]:
dataset.to_numpy()

array([[0,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-30-59.mp3'],
       [1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [2,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-262-291.mp3'],
       ...,
       [25860,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-30-59.mp3'],
       [25861,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-59-88.mp3'],
       [25862,
        '8/jacob_heringman-blame_not_my_lute-58-a_toy_for_monica_bishop-0-29.mp3']],
      dtype=object)

In [13]:
train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

In [14]:
## Train

In [15]:
train = dataset.sample(round(train_ratio*len(dataset.index)),random_state=10)
train

idx                                           mp3_path
14060  14060  f/american_baroque-the_four_seasons_by_vivaldi...
23089  23089  f/the_napoleon_blown_aparts-thrill_hype-13-tri...
23418  23418  0/paul_berget-the_siena_manuscript_on_steel_st...
11812  11812  e/sun_palace-into_heaven-06-are_you_thinking_o...
6480    6480  2/indidginus-as_above_so_below-03-nimbus-88-11...
...      ...                                                ...
19495  19495  d/tom_paul-there_is_no_map-10-guess_i_didnt_tr...
2357    2357  a/electric_frankenstein-the_time_is_now-01-tee...
12802  12802  5/paul_avgerinos-muse_of_the_round_sky-06-muse...
19829  19829  4/paul_avgerinos-sky_of_grace-10-our_cathedral...
11854  11854                 0/solace-iman-06-azure-233-262.mp3

[16886 rows x 2 columns]

In [16]:
dataset_train = train.to_numpy()
np.save(open('../split/mtat/train.npy', 'wb'), dataset_train)
dataset_train

array([[14060,
        'f/american_baroque-the_four_seasons_by_vivaldi-07-concerto_no_3_in_f_major_rv_293_autumn__allegro-30-59.mp3'],
       [23089,
        'f/the_napoleon_blown_aparts-thrill_hype-13-trippin_inside_my_head-59-88.mp3'],
       [23418,
        '0/paul_berget-the_siena_manuscript_on_steel_string_guitar-14-recercar_14_steel_string_guitar-30-59.mp3'],
       ...,
       [12802,
        '5/paul_avgerinos-muse_of_the_round_sky-06-muse_of_the_round_sky-146-175.mp3'],
       [19829,
        '4/paul_avgerinos-sky_of_grace-10-our_cathedral-146-175.mp3'],
       [11854, '0/solace-iman-06-azure-233-262.mp3']], dtype=object)

In [17]:
mini_train = train.sample(len(train.index) // 10,random_state=10)
mini_train

idx                                           mp3_path
9215    9215  b/rob_costlow-sophomore_jinx-04-summer_garden-...
16308  16308              8/ivilion-terean-08-hthar-291-320.mp3
12505  12505  0/jeffrey_luck_lucas-what_we_whisper-06-in_the...
15084  15084     2/solace-ahsas-07-redemption_128_84-88-117.mp3
18547  18547  d/beth_quist-shall_we_dance-09-ritual-117-146.mp3
...      ...                                                ...
4598    4598  5/paul_avgerinos-muse_of_the_round_sky-02-song...
2114    2114  6/paul_beier-michelagnolo_galilei-01-sonate_in...
16462  16462  4/tilopa-kyotaku_live-08-kyotaku_klangschale-0...
6026    6026             9/strojovna_07-iii-03-gvgh-262-291.mp3
17029  17029   3/very_large_array-stuff-08-slow_there-59-88.mp3

[1688 rows x 2 columns]

In [18]:
dataset_mini_train = mini_train.to_numpy()
np.save(open('../split/mtat-mini/train.npy', 'wb'), dataset_mini_train)
dataset_mini_train

array([[9215, 'b/rob_costlow-sophomore_jinx-04-summer_garden-59-88.mp3'],
       [16308, '8/ivilion-terean-08-hthar-291-320.mp3'],
       [12505,
        '0/jeffrey_luck_lucas-what_we_whisper-06-in_the_stars_whirling-117-146.mp3'],
       ...,
       [16462, '4/tilopa-kyotaku_live-08-kyotaku_klangschale-0-29.mp3'],
       [6026, '9/strojovna_07-iii-03-gvgh-262-291.mp3'],
       [17029, '3/very_large_array-stuff-08-slow_there-59-88.mp3']],
      dtype=object)

In [19]:
## Valid

In [20]:
valid = dataset.drop(train.index)
valid = valid.sample(round(valid_ratio*len(dataset.index)),random_state=10)
valid

idx                                           mp3_path
5525    5525  e/dac_crowell-within_this_space-03-cantillatio...
19836  19836       a/plunkett-14_days-10-out_at_sea-175-204.mp3
3080    3080  d/paul_avgerinos-maya__the_great_katun-02-dawn...
14570  14570  5/arthur_yoria-of_the_lovely-07-its_now_someth...
4878    4878        1/tim_rayborn-ashek-02-tuna_neico-30-59.mp3
...      ...                                                ...
13281  13281  6/doc_rossi-demarzi6_sonatas_for_cetra_o_kitar...
25116  25116  e/steven_devine-portrait_of_an_english_harpsic...
10611  10611  1/suzanne_teng-mystic_journey-05-lhasa_love-59...
20018  20018  e/burning_babylon-stereo_mash_up-10-rude_boots...
24537  24537  1/vito_paternoster-cd1bach_cello_suites-17-sui...

[2111 rows x 2 columns]

In [21]:
dataset_valid = valid.to_numpy()
np.save(open('../split/mtat/valid.npy', 'wb'), dataset_valid)
dataset_valid

array([[5525,
        'e/dac_crowell-within_this_space-03-cantillation-726-755.mp3'],
       [19836, 'a/plunkett-14_days-10-out_at_sea-175-204.mp3'],
       [3080,
        'd/paul_avgerinos-maya__the_great_katun-02-dawn_of_the_gods_part_2-262-291.mp3'],
       ...,
       [10611, '1/suzanne_teng-mystic_journey-05-lhasa_love-59-88.mp3'],
       [20018,
        'e/burning_babylon-stereo_mash_up-10-rude_boots-59-88.mp3'],
       [24537,
        '1/vito_paternoster-cd1bach_cello_suites-17-suite_vi_in_re_magiore__gavotte_i_e_ii-0-29.mp3']],
      dtype=object)

In [22]:
mini_valid = valid.sample(len(valid.index) // 10,random_state=10)
mini_valid

idx                                           mp3_path
13227  13227    3/etherfysh-box_of_fysh-06-sidewalk-436-465.mp3
20478  20478          6/curandero-curandero-11-adios-88-117.mp3
24784  24784  9/janine_johnson-german_keyboard_masters-18-vo...
12571  12571  c/liquid_zen-oscilloscope-06-kitano_zoom-117-1...
15933  15933  e/shira_kammen-music_of_waters-08-boathag-30-5...
...      ...                                                ...
8225    8225  0/voices_of_music-an_evening_with_bach-04-ich_...
2849    2849    f/strojovna_07-dirnix-02-basetra_noje-30-59.mp3
4975    4975  5/paul_beier-simone_molinaro-02-ung_gaij_bergi...
16901  16901   6/barry_phillips-trad-08-rondopolska-117-146.mp3
15314  15314  5/stargarden-step_off-07-step_out_to_the_stars...

[211 rows x 2 columns]

In [23]:
dataset_mini_valid = mini_valid.to_numpy()
np.save(open('../split/mtat-mini/valid.npy', 'wb'), dataset_mini_valid)
dataset_mini_valid

array([[13227, '3/etherfysh-box_of_fysh-06-sidewalk-436-465.mp3'],
       [20478, '6/curandero-curandero-11-adios-88-117.mp3'],
       [24784,
        '9/janine_johnson-german_keyboard_masters-18-von_der_geburt_christi_pachelbel-88-117.mp3'],
       [12571, 'c/liquid_zen-oscilloscope-06-kitano_zoom-117-146.mp3'],
       [15933, 'e/shira_kammen-music_of_waters-08-boathag-30-59.mp3'],
       [3813,
        '9/various_artists-the_2007_magnatune_records_sampler-02-moonrise_yongen-30-59.mp3'],
       [23557, 'f/glen_bledsoe-octopants-14-trainbuktu-117-146.mp3'],
       [10081,
        '2/maryse_carlin-rameau__pieces_de_clavecin_en_concerts__forqueray_suites_4_and_5-05-deuxieme_concert__la_boucon_rameau-0-29.mp3'],
       [16123,
        '4/orinda-airs_de_cour-08-enfin_la_beaute_que_jadore_etienne_moulinie-233-262.mp3'],
       [14596, '4/mutandina-mutandina-07-la_casita_del_amor-117-146.mp3'],
       [21771, '7/rocket_city_riot-pop_killer-12-cut_me_out-175-204.mp3'],
       [8120,
        '

In [24]:
test = dataset.drop(train.index)
test = test.drop(valid.index)
test

idx                                           mp3_path
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
14        14  f/the_headroom_project-jetuton_andawai-01-lind...
21        21  9/american_bach_soloists-heinrich_schutz__musi...
32        32  9/american_bach_soloists-heinrich_schutz__musi...
74        74  5/new_york_consort_of_viols-dances_and_canzona...
...      ...                                                ...
25796  25796  c/edward_martin-art_of_the_lute_in_renaissance...
25835  25835  3/musica_franca-boismortier__sonatas_for_two_b...
25838  25838  8/jacob_heringman-blame_not_my_lute-39-tiente_...
25845  25845  8/jacob_heringman-blame_not_my_lute-49-grene_s...
25851  25851  7/magnaloops-world_loops_2-54-osdmichaelmasley...

[2111 rows x 2 columns]

In [25]:
dataset_test = test.to_numpy()
np.save(open('../split/mtat/test.npy', 'wb'), dataset_test)
dataset_test

array([[1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [14,
        'f/the_headroom_project-jetuton_andawai-01-linda_morena-59-88.mp3'],
       [21,
        '9/american_bach_soloists-heinrich_schutz__musicalische_exequien-01-musicalische_exequien_swv_279_teil_i_concert_in_form_einer_teutschen_begrabnismissa-320-349.mp3'],
       ...,
       [25838,
        '8/jacob_heringman-blame_not_my_lute-39-tiente_alora-0-29.mp3'],
       [25845,
        '8/jacob_heringman-blame_not_my_lute-49-grene_sleves-0-29.mp3'],
       [25851,
        '7/magnaloops-world_loops_2-54-osdmichaelmasley644-0-29.mp3']],
      dtype=object)

In [26]:
mini_test = test.sample(len(test.index) // 10,random_state=10)
mini_test

idx                                           mp3_path
25013  25013  e/philharmonia_baroque_orchestra-handel__atala...
14425  14425  0/williamson-a_few_things_to_hear_before_we_al...
23050  23050  c/william_brooks-blue_ribbon__the_best_of_will...
3167    3167  e/shira_kammen-music_of_waters-02-downstream-1...
4734    4734  4/falling_you-touch-02-the_art_of_possession_n...
...      ...                                                ...
14857  14857  4/dj_markitos-evolution_of_the_mind-07-norther...
9945    9945  d/shira_kammen-mistral-05-cominciamento_di_gio...
268      268  b/lisa_debenedictis-mixter_one-01-belowduremix...
7841    7841  5/burnshee_thornside-rock_this_moon-04-dear_er...
22565  22565  8/magnatune-red_hat_summit_compilation-13-c__l...

[211 rows x 2 columns]

In [27]:
dataset_mini_test = mini_test.to_numpy()
np.save(open('../split/mtat-mini/test.npy', 'wb'), dataset_mini_test)
dataset_mini_test

array([[25013,
        'e/philharmonia_baroque_orchestra-handel__atalanta_cd1-20-coro_oggi_rimbombano_di_feste-117-146.mp3'],
       [14425,
        '0/williamson-a_few_things_to_hear_before_we_all_blow_up-07-glitch_cowboy_local_16044-117-146.mp3'],
       [23050,
        'c/william_brooks-blue_ribbon__the_best_of_william_brooks-13-the_fox_guarding_the_henhouse-88-117.mp3'],
       [3167, 'e/shira_kammen-music_of_waters-02-downstream-146-175.mp3'],
       [4734,
        '4/falling_you-touch-02-the_art_of_possession_no_escape-30-59.mp3'],
       [7736,
        '4/american_bach_soloists-j_s__bach__favorite_cantatas-04-chorale__zion_hort_die_wachter_singen-204-233.mp3'],
       [17021, '9/wicked_boy-chemistry-08-slomo-30-59.mp3'],
       [4611,
        '4/magnatune-romantic_dinner_classical_compilation-02-sonnerie__from_handel_trio_sonatas-552-581.mp3'],
       [1894,
        'e/dac_crowell-within_this_space-01-running_depth-146-175.mp3'],
       [20772,
        '2/maryse_carlin-rameau__p