In [1]:
import numpy as np
import pandas as pd

In [2]:
broken_tracks = [
    "6/norine_braun-now_and_zen-08-gently-117-146.mp3",
    "8/jacob_heringman-josquin_des_prez_lute_settings-19-gintzler__pater_noster-204-233.mp3",
    "9/american_baroque-dances_and_suites_of_rameau_and_couperin-25-le_petit_rien_xiveme_ordre_couperin-88-117.mp3",
    "c/domased-new_memories-07-first_sun_rays-233-262.mp3",
    "d/tim_rayborn-chordae-04-sempr_alegria-784-813.mp3"
]

In [3]:
adnotations = pd.read_csv('../data/mtat/annotations_final.csv', sep='\t')
adnotations = adnotations[~adnotations["mp3_path"].isin(broken_tracks)]
adnotations

clip_id  no voice  singer  duet  plucking  hard rock  world  bongos  \
0            2         0       0     0         0          0      0       0   
1            6         0       0     0         0          0      0       0   
2           10         0       0     0         0          0      0       0   
3           11         0       0     0         0          0      0       0   
4           12         0       0     0         0          0      0       0   
...        ...       ...     ...   ...       ...        ...    ...     ...   
25858    58899         0       0     0         0          0      0       0   
25859    58906         0       0     0         0          0      0       0   
25860    58907         0       0     0         0          0      0       0   
25861    58908         0       0     0         0          0      0       0   
25862    58915         0       0     0         0          0      0       0   

       harpsichord  female singing  ...  rap  metal  hip hop  quick  water  \
0                0               0  ...    0      0        0      0      0   
1                0               0  ...    0      0        0      0      0   
2                0               0  ...    0      0        0      0      0   
3                0               0  ...    0      0        0      0      0   
4                0               0  ...    0      0        0      0      0   
...            ...             ...  ...  ...    ...      ...    ...    ...   
25858            0               0  ...    0      0        0      0      0   
25859            0               0  ...    0      0        0      0      0   
25860            0               0  ...    0      0        0      0      0   
25861            0               0  ...    0      0        0      0      0   
25862            0               0  ...    0      0        0      0      0   

       baroque  women  fiddle  english  \
0            0      0       0        0   
1            1      0       0        0   
2            0      0       0        0   
3            0      0       0        0   
4            0      0       0        0   
...        ...    ...     ...      ...   
25858        0      0       0        0   
25859        0      0       0        0   
25860        0      0       0        0   
25861        0      0       0        0   
25862        0      0       0        0   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[25859 rows x 190 columns]

In [4]:
clip_info = pd.read_csv('../data/mtat/clip_info_final.csv', sep='\t')
clip_info

clip_id  track_number                    title                  artist  \
0            2             1           BWV54 - I Aria  American Bach Soloists   
1            6             1           BWV54 - I Aria  American Bach Soloists   
2           10             1           BWV54 - I Aria  American Bach Soloists   
3           11             1           BWV54 - I Aria  American Bach Soloists   
4           12             1           BWV54 - I Aria  American Bach Soloists   
...        ...           ...                      ...                     ...   
31377    58899            56            La Bressanina         Jacob Heringman   
31378    58906            57       Lost is my Lyberty         Jacob Heringman   
31379    58907            57       Lost is my Lyberty         Jacob Heringman   
31380    58908            57       Lost is my Lyberty         Jacob Heringman   
31381    58915            58  A Toy for Monica Bishop         Jacob Heringman   

                         album  \
0      J.S. Bach Solo Cantatas   
1      J.S. Bach Solo Cantatas   
2      J.S. Bach Solo Cantatas   
3      J.S. Bach Solo Cantatas   
4      J.S. Bach Solo Cantatas   
...                        ...   
31377        Blame Not My Lute   
31378        Blame Not My Lute   
31379        Blame Not My Lute   
31380        Blame Not My Lute   
31381        Blame Not My Lute   

                                                     url  segmentStart  \
0      http://www.magnatune.com/artists/albums/abs-so...            30   
1      http://www.magnatune.com/artists/albums/abs-so...           146   
2      http://www.magnatune.com/artists/albums/abs-so...           262   
3      http://www.magnatune.com/artists/albums/abs-so...           291   
4      http://www.magnatune.com/artists/albums/abs-so...           320   
...                                                  ...           ...   
31377  http://www.magnatune.com/artists/albums/hering...            88   
31378  http://www.magnatune.com/artists/albums/hering...             0   
31379  http://www.magnatune.com/artists/albums/hering...            30   
31380  http://www.magnatune.com/artists/albums/hering...            59   
31381  http://www.magnatune.com/artists/albums/hering...             0   

       segmentEnd                                       original_url  \
0              59  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
1             175  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
2             291  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
3             320  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
4             349  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
...           ...                                                ...   
31377         117  http://he3.magnatune.com/all/56-La%20Bressanin...   
31378          29  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31379          59  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31380          88  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31381          29  http://he3.magnatune.com/all/58-A%20Toy%20for%...   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
31377  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
31378  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31379  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31380  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31381  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[31382 rows x 10 columns]

# 50 tags with the largest quantity in dataset

In [5]:
tags = adnotations.filter(regex='[^(clip_id|mp3_path)]').sum().nlargest(50).keys().to_numpy('str')
tags

array(['guitar', 'classical', 'slow', 'techno', 'strings', 'drums',
       'electronic', 'rock', 'fast', 'piano', 'ambient', 'beat', 'violin',
       'vocal', 'synth', 'female', 'indian', 'opera', 'male', 'singing',
       'vocals', 'no vocals', 'harpsichord', 'loud', 'quiet', 'flute',
       'woman', 'male vocal', 'no vocal', 'pop', 'soft', 'sitar', 'solo',
       'man', 'classic', 'choir', 'voice', 'new age', 'dance',
       'male voice', 'female vocal', 'beats', 'harp', 'cello', 'no voice',
       'weird', 'country', 'female voice', 'metal', 'choral'],
      dtype='<U12')

# Binary tags

In [6]:
binary = adnotations[tags]
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
0           0          1     0       0        1      0           0     0   
1           0          1     0       0        1      0           0     0   
2           0          1     0       0        0      0           0     0   
3           0          0     0       0        0      0           0     0   
4           0          1     0       0        1      0           0     0   
...       ...        ...   ...     ...      ...    ...         ...   ...   
25858       1          0     0       0        0      0           0     0   
25859       1          0     1       0        1      0           0     0   
25860       1          1     1       0        1      0           0     0   
25861       1          1     1       0        0      0           0     0   
25862       1          1     1       0        0      0           0     0   

       fast  piano  ...  female vocal  beats  harp  cello  no voice  weird  \
0         0      0  ...             0      0     0      0         0      0   
1         0      0  ...             0      0     0      0         0      0   
2         0      0  ...             0      0     0      0         0      0   
3         0      0  ...             0      0     0      0         0      0   
4         0      0  ...             0      0     0      0         0      0   
...     ...    ...  ...           ...    ...   ...    ...       ...    ...   
25858     0      0  ...             0      0     0      0         0      0   
25859     0      0  ...             0      0     1      0         0      0   
25860     0      0  ...             0      0     0      0         0      0   
25861     0      0  ...             0      0     0      0         0      0   
25862     0      0  ...             0      0     0      0         0      0   

       country  female voice  metal  choral  
0            0             0      0       0  
1            0             0      0       0  
2            0             0      0       0  
3            0             0      0       0  
4            0             0      0       0  
...        ...           ...    ...     ...  
25858        0             0      0       0  
25859        0             0      0       0  
25860        0             0      0       0  
25861        0             0      0       0  
25862        0             0      0       0  

[25859 rows x 50 columns]

In [7]:
indexes_to_keep = binary[binary.sum(axis=1) != 0].index.values
binary = binary[binary.index.isin(indexes_to_keep)]
adnotations = adnotations[adnotations.index.isin(indexes_to_keep)]
binary.reset_index()
adnotations.reset_index()
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
0           0          1     0       0        1      0           0     0   
1           0          1     0       0        1      0           0     0   
2           0          1     0       0        0      0           0     0   
3           0          0     0       0        0      0           0     0   
4           0          1     0       0        1      0           0     0   
...       ...        ...   ...     ...      ...    ...         ...   ...   
25858       1          0     0       0        0      0           0     0   
25859       1          0     1       0        1      0           0     0   
25860       1          1     1       0        1      0           0     0   
25861       1          1     1       0        0      0           0     0   
25862       1          1     1       0        0      0           0     0   

       fast  piano  ...  female vocal  beats  harp  cello  no voice  weird  \
0         0      0  ...             0      0     0      0         0      0   
1         0      0  ...             0      0     0      0         0      0   
2         0      0  ...             0      0     0      0         0      0   
3         0      0  ...             0      0     0      0         0      0   
4         0      0  ...             0      0     0      0         0      0   
...     ...    ...  ...           ...    ...   ...    ...       ...    ...   
25858     0      0  ...             0      0     0      0         0      0   
25859     0      0  ...             0      0     1      0         0      0   
25860     0      0  ...             0      0     0      0         0      0   
25861     0      0  ...             0      0     0      0         0      0   
25862     0      0  ...             0      0     0      0         0      0   

       country  female voice  metal  choral  
0            0             0      0       0  
1            0             0      0       0  
2            0             0      0       0  
3            0             0      0       0  
4            0             0      0       0  
...        ...           ...    ...     ...  
25858        0             0      0       0  
25859        0             0      0       0  
25860        0             0      0       0  
25861        0             0      0       0  
25862        0             0      0       0  

[21107 rows x 50 columns]

In [8]:
binary[binary.sum(axis=1) != 0].index

Int64Index([    0,     1,     2,     3,     4,     5,     7,     8,    10,
               11,
            ...
            25853, 25854, 25855, 25856, 25857, 25858, 25859, 25860, 25861,
            25862],
           dtype='int64', length=21107)

In [9]:
binary_np = binary.to_numpy()
print(binary_np.shape)
binary_np

(21107, 50)


array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

# Spliting dataset to train, valid and test datasets

In [10]:
dataset = pd.DataFrame(adnotations.mp3_path, columns=['idx', 'mp3_path'])
dataset["idx"] = dataset.index
dataset

idx                                           mp3_path
0          0  f/american_bach_soloists-j_s__bach_solo_cantat...
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
2          2  f/american_bach_soloists-j_s__bach_solo_cantat...
3          3  f/american_bach_soloists-j_s__bach_solo_cantat...
4          4  f/american_bach_soloists-j_s__bach_solo_cantat...
...      ...                                                ...
25858  25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...
25859  25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25860  25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25861  25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25862  25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...

[21107 rows x 2 columns]

In [11]:
dataset.to_numpy()

array([[0,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-30-59.mp3'],
       [1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [2,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-262-291.mp3'],
       ...,
       [25860,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-30-59.mp3'],
       [25861,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-59-88.mp3'],
       [25862,
        '8/jacob_heringman-blame_not_my_lute-58-a_toy_for_monica_bishop-0-29.mp3']],
      dtype=object)

In [12]:
train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

In [13]:
## Train

In [14]:
train = dataset.sample(round(train_ratio*len(dataset.index)),random_state=10)
train

idx                                           mp3_path
14060  14060  f/american_baroque-the_four_seasons_by_vivaldi...
23087  23087  4/norine_braun-modern_anguish-13-tips_and_not_...
23417  23417  0/paul_berget-the_siena_manuscript_on_steel_st...
11812  11812  e/sun_palace-into_heaven-06-are_you_thinking_o...
6480    6480  2/indidginus-as_above_so_below-03-nimbus-88-11...
...      ...                                                ...
2357    2357  a/electric_frankenstein-the_time_is_now-01-tee...
12802  12802  5/paul_avgerinos-muse_of_the_round_sky-06-muse...
19829  19829  4/paul_avgerinos-sky_of_grace-10-our_cathedral...
11854  11854                 0/solace-iman-06-azure-233-262.mp3
17798  17798  2/jami_sieber-lush_mechanique-09-dancing_at_th...

[16886 rows x 2 columns]

In [15]:
dataset_train = train.to_numpy()
np.save(open('../split/mtat/train.npy', 'wb'), dataset_train)
dataset_train

array([[14060,
        'f/american_baroque-the_four_seasons_by_vivaldi-07-concerto_no_3_in_f_major_rv_293_autumn__allegro-30-59.mp3'],
       [23087,
        '4/norine_braun-modern_anguish-13-tips_and_not_trouble-59-88.mp3'],
       [23417,
        '0/paul_berget-the_siena_manuscript_on_steel_string_guitar-14-recercar_14_steel_string_guitar-0-29.mp3'],
       ...,
       [19829,
        '4/paul_avgerinos-sky_of_grace-10-our_cathedral-146-175.mp3'],
       [11854, '0/solace-iman-06-azure-233-262.mp3'],
       [17798,
        '2/jami_sieber-lush_mechanique-09-dancing_at_the_temple_gate-436-465.mp3']],
      dtype=object)

In [16]:
mini_train = train.sample(len(train.index) // 10,random_state=10)
mini_train

idx                                           mp3_path
9215    9215  b/rob_costlow-sophomore_jinx-04-summer_garden-...
16308  16308              8/ivilion-terean-08-hthar-291-320.mp3
12505  12505  0/jeffrey_luck_lucas-what_we_whisper-06-in_the...
15084  15084     2/solace-ahsas-07-redemption_128_84-88-117.mp3
18547  18547  d/beth_quist-shall_we_dance-09-ritual-117-146.mp3
...      ...                                                ...
4598    4598  5/paul_avgerinos-muse_of_the_round_sky-02-song...
2114    2114  6/paul_beier-michelagnolo_galilei-01-sonate_in...
16462  16462  4/tilopa-kyotaku_live-08-kyotaku_klangschale-0...
6026    6026             9/strojovna_07-iii-03-gvgh-262-291.mp3
17029  17029   3/very_large_array-stuff-08-slow_there-59-88.mp3

[1688 rows x 2 columns]

In [17]:
dataset_mini_train = mini_train.to_numpy()
np.save(open('../split/mtat-mini/train.npy', 'wb'), dataset_mini_train)
dataset_mini_train

array([[9215, 'b/rob_costlow-sophomore_jinx-04-summer_garden-59-88.mp3'],
       [16308, '8/ivilion-terean-08-hthar-291-320.mp3'],
       [12505,
        '0/jeffrey_luck_lucas-what_we_whisper-06-in_the_stars_whirling-117-146.mp3'],
       ...,
       [16462, '4/tilopa-kyotaku_live-08-kyotaku_klangschale-0-29.mp3'],
       [6026, '9/strojovna_07-iii-03-gvgh-262-291.mp3'],
       [17029, '3/very_large_array-stuff-08-slow_there-59-88.mp3']],
      dtype=object)

In [18]:
## Valid

In [19]:
valid = dataset.drop(train.index)
valid = valid.sample(round(valid_ratio*len(dataset.index)),random_state=10)
valid

idx                                           mp3_path
5525    5525  e/dac_crowell-within_this_space-03-cantillatio...
19840  19840  6/strojovna_07-mirnix-10-out_clipping-175-204.mp3
3080    3080  d/paul_avgerinos-maya__the_great_katun-02-dawn...
14570  14570  5/arthur_yoria-of_the_lovely-07-its_now_someth...
4878    4878        1/tim_rayborn-ashek-02-tuna_neico-30-59.mp3
...      ...                                                ...
13281  13281  6/doc_rossi-demarzi6_sonatas_for_cetra_o_kitar...
25148  25148  4/american_bach_soloists-j_s__bach__favorite_c...
10611  10611  1/suzanne_teng-mystic_journey-05-lhasa_love-59...
20024  20024               0/solace-iman-10-saalik_2-88-117.mp3
24554  24554  d/drevo-christian_themes_in_ukrainian_folk_son...

[2111 rows x 2 columns]

In [20]:
dataset_valid = valid.to_numpy()
np.save(open('../split/mtat/valid.npy', 'wb'), dataset_valid)
dataset_valid

array([[5525,
        'e/dac_crowell-within_this_space-03-cantillation-726-755.mp3'],
       [19840, '6/strojovna_07-mirnix-10-out_clipping-175-204.mp3'],
       [3080,
        'd/paul_avgerinos-maya__the_great_katun-02-dawn_of_the_gods_part_2-262-291.mp3'],
       ...,
       [10611, '1/suzanne_teng-mystic_journey-05-lhasa_love-59-88.mp3'],
       [20024, '0/solace-iman-10-saalik_2-88-117.mp3'],
       [24554,
        'd/drevo-christian_themes_in_ukrainian_folk_songs-17-through_the_wide_field_through_the_deep_sea-59-88.mp3']],
      dtype=object)

In [21]:
mini_valid = valid.sample(len(valid.index) // 10,random_state=10)
mini_valid

idx                                           mp3_path
13227  13227    3/etherfysh-box_of_fysh-06-sidewalk-436-465.mp3
20487  20487  e/hans_christian-phantoms-11-aftermath-233-262...
25396  25396  f/jacob_heringman_and_catherine_king-luis_mila...
12571  12571  c/liquid_zen-oscilloscope-06-kitano_zoom-117-1...
15933  15933  e/shira_kammen-music_of_waters-08-boathag-30-5...
...      ...                                                ...
8225    8225  0/voices_of_music-an_evening_with_bach-04-ich_...
2849    2849    f/strojovna_07-dirnix-02-basetra_noje-30-59.mp3
4975    4975  5/paul_beier-simone_molinaro-02-ung_gaij_bergi...
16901  16901   6/barry_phillips-trad-08-rondopolska-117-146.mp3
15314  15314  5/stargarden-step_off-07-step_out_to_the_stars...

[211 rows x 2 columns]

In [22]:
dataset_mini_valid = mini_valid.to_numpy()
np.save(open('../split/mtat-mini/valid.npy', 'wb'), dataset_mini_valid)
dataset_mini_valid

array([[13227, '3/etherfysh-box_of_fysh-06-sidewalk-436-465.mp3'],
       [20487, 'e/hans_christian-phantoms-11-aftermath-233-262.mp3'],
       [25396,
        'f/jacob_heringman_and_catherine_king-luis_milan_el_maestro-23-romance_sospirastes_baldovinos-117-146.mp3'],
       [12571, 'c/liquid_zen-oscilloscope-06-kitano_zoom-117-146.mp3'],
       [15933, 'e/shira_kammen-music_of_waters-08-boathag-30-59.mp3'],
       [3813,
        '9/various_artists-the_2007_magnatune_records_sampler-02-moonrise_yongen-30-59.mp3'],
       [23554, 'f/glen_bledsoe-octopants-14-trainbuktu-30-59.mp3'],
       [10081,
        '2/maryse_carlin-rameau__pieces_de_clavecin_en_concerts__forqueray_suites_4_and_5-05-deuxieme_concert__la_boucon_rameau-0-29.mp3'],
       [16123,
        '4/orinda-airs_de_cour-08-enfin_la_beaute_que_jadore_etienne_moulinie-233-262.mp3'],
       [14596, '4/mutandina-mutandina-07-la_casita_del_amor-117-146.mp3'],
       [21778, '8/mercy_machine-mercy_machine-12-der_traum-88-117.mp3'],
 

In [23]:
test = dataset.drop(train.index)
test = test.drop(valid.index)
test

idx                                           mp3_path
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
14        14  f/the_headroom_project-jetuton_andawai-01-lind...
21        21  9/american_bach_soloists-heinrich_schutz__musi...
32        32  9/american_bach_soloists-heinrich_schutz__musi...
74        74  5/new_york_consort_of_viols-dances_and_canzona...
...      ...                                                ...
25796  25796  c/edward_martin-art_of_the_lute_in_renaissance...
25803  25803  1/richard_savino-murcia__danza_y_diferencias-3...
25828  25828  8/jacob_heringman-blame_not_my_lute-36-passa_m...
25835  25835  3/musica_franca-boismortier__sonatas_for_two_b...
25846  25846  7/magnaloops-world_loops_2-49-osfjaykishor580-...

[2110 rows x 2 columns]

In [24]:
dataset_test = test.to_numpy()
np.save(open('../split/mtat/test.npy', 'wb'), dataset_test)
dataset_test

array([[1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [14,
        'f/the_headroom_project-jetuton_andawai-01-linda_morena-59-88.mp3'],
       [21,
        '9/american_bach_soloists-heinrich_schutz__musicalische_exequien-01-musicalische_exequien_swv_279_teil_i_concert_in_form_einer_teutschen_begrabnismissa-320-349.mp3'],
       ...,
       [25828,
        '8/jacob_heringman-blame_not_my_lute-36-passa_mesure_galiarde-30-59.mp3'],
       [25835,
        '3/musica_franca-boismortier__sonatas_for_two_bassoons_and_continuo-38-chaconne_in_a_major_op__66-30-59.mp3'],
       [25846, '7/magnaloops-world_loops_2-49-osfjaykishor580-0-29.mp3']],
      dtype=object)

In [25]:
mini_test = test.sample(len(test.index) // 10,random_state=10)
mini_test

idx                                           mp3_path
1642    1642  1/the_rajdhani_quartet-the_gandhi_memorial_con...
2678    2678  9/philharmonia_baroque_orchestra-jake_heggie__...
14404  14404  f/professor_armchair-too_much_mustard-07-funer...
8134    8134             0/beth_quist-silver-04-grace-59-88.mp3
21725  21725  0/ensemble_vermillian-stolen_jewels-12-buxtehu...
...      ...                                                ...
22996  22996  1/vito_paternoster-cd1bach_cello_suites-13-sui...
22039  22039  f/magnatune-relaxation_spa-12-northeastern_cor...
15691  15691  c/lvx_nova-lvx_nova-08-in_memory_of_magick_mic...
7714    7714  b/la_primavera-english_renaissance_music-04-ce...
14556  14556  8/william_brooks-buffalo_treason-07-is_this_en...

[211 rows x 2 columns]

In [26]:
dataset_mini_test = mini_test.to_numpy()
np.save(open('../split/mtat-mini/test.npy', 'wb'), dataset_mini_test)
dataset_mini_test

array([[1642,
        '1/the_rajdhani_quartet-the_gandhi_memorial_concert-01-raga_hansa_kalyani-1799-1828.mp3'],
       [2678,
        '9/philharmonia_baroque_orchestra-jake_heggie__to_hell_and_back-02-a_phone_call_and_a_letter_from_arizona-30-59.mp3'],
       [14404,
        'f/professor_armchair-too_much_mustard-07-funeral_march_of_a_marionette-117-146.mp3'],
       [8134, '0/beth_quist-silver-04-grace-59-88.mp3'],
       [21725,
        '0/ensemble_vermillian-stolen_jewels-12-buxtehude_sonata_ii_op_i_lentovivace-117-146.mp3'],
       [5708, '1/ambient_teknology-phoenix-03-deeper-175-204.mp3'],
       [4529,
        '2/ensemble_mirable-conversations_galantes-02-sonata_iii_in_d_minor_larghetto-88-117.mp3'],
       [24418,
        '2/shira_kammen-the_almanac-17-green_grows_the_holly-175-204.mp3'],
       [9307,
        'e/briddes_roune-lenten_is_come-04-the_milde_lomb-233-262.mp3'],
       [3413,
        'f/norine_braun-and_the_mood_swings-02-give_me_love-88-117.mp3'],
       [13878,
 