In [1]:
import numpy as np
import pandas as pd

In [2]:
adnotations = pd.read_csv('../data/mtat/annotations_final.csv', sep='\t')
adnotations

clip_id  no voice  singer  duet  plucking  hard rock  world  bongos  \
0            2         0       0     0         0          0      0       0   
1            6         0       0     0         0          0      0       0   
2           10         0       0     0         0          0      0       0   
3           11         0       0     0         0          0      0       0   
4           12         0       0     0         0          0      0       0   
...        ...       ...     ...   ...       ...        ...    ...     ...   
25858    58899         0       0     0         0          0      0       0   
25859    58906         0       0     0         0          0      0       0   
25860    58907         0       0     0         0          0      0       0   
25861    58908         0       0     0         0          0      0       0   
25862    58915         0       0     0         0          0      0       0   

       harpsichord  female singing  ...  rap  metal  hip hop  quick  water  \
0                0               0  ...    0      0        0      0      0   
1                0               0  ...    0      0        0      0      0   
2                0               0  ...    0      0        0      0      0   
3                0               0  ...    0      0        0      0      0   
4                0               0  ...    0      0        0      0      0   
...            ...             ...  ...  ...    ...      ...    ...    ...   
25858            0               0  ...    0      0        0      0      0   
25859            0               0  ...    0      0        0      0      0   
25860            0               0  ...    0      0        0      0      0   
25861            0               0  ...    0      0        0      0      0   
25862            0               0  ...    0      0        0      0      0   

       baroque  women  fiddle  english  \
0            0      0       0        0   
1            1      0       0        0   
2            0      0       0        0   
3            0      0       0        0   
4            0      0       0        0   
...        ...    ...     ...      ...   
25858        0      0       0        0   
25859        0      0       0        0   
25860        0      0       0        0   
25861        0      0       0        0   
25862        0      0       0        0   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[25863 rows x 190 columns]

In [3]:
clip_info = pd.read_csv('../data/mtat/clip_info_final.csv', sep='\t')
clip_info

clip_id  track_number                    title                  artist  \
0            2             1           BWV54 - I Aria  American Bach Soloists   
1            6             1           BWV54 - I Aria  American Bach Soloists   
2           10             1           BWV54 - I Aria  American Bach Soloists   
3           11             1           BWV54 - I Aria  American Bach Soloists   
4           12             1           BWV54 - I Aria  American Bach Soloists   
...        ...           ...                      ...                     ...   
31377    58899            56            La Bressanina         Jacob Heringman   
31378    58906            57       Lost is my Lyberty         Jacob Heringman   
31379    58907            57       Lost is my Lyberty         Jacob Heringman   
31380    58908            57       Lost is my Lyberty         Jacob Heringman   
31381    58915            58  A Toy for Monica Bishop         Jacob Heringman   

                         album  \
0      J.S. Bach Solo Cantatas   
1      J.S. Bach Solo Cantatas   
2      J.S. Bach Solo Cantatas   
3      J.S. Bach Solo Cantatas   
4      J.S. Bach Solo Cantatas   
...                        ...   
31377        Blame Not My Lute   
31378        Blame Not My Lute   
31379        Blame Not My Lute   
31380        Blame Not My Lute   
31381        Blame Not My Lute   

                                                     url  segmentStart  \
0      http://www.magnatune.com/artists/albums/abs-so...            30   
1      http://www.magnatune.com/artists/albums/abs-so...           146   
2      http://www.magnatune.com/artists/albums/abs-so...           262   
3      http://www.magnatune.com/artists/albums/abs-so...           291   
4      http://www.magnatune.com/artists/albums/abs-so...           320   
...                                                  ...           ...   
31377  http://www.magnatune.com/artists/albums/hering...            88   
31378  http://www.magnatune.com/artists/albums/hering...             0   
31379  http://www.magnatune.com/artists/albums/hering...            30   
31380  http://www.magnatune.com/artists/albums/hering...            59   
31381  http://www.magnatune.com/artists/albums/hering...             0   

       segmentEnd                                       original_url  \
0              59  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
1             175  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
2             291  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
3             320  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
4             349  http://he3.magnatune.com/all/01--BWV54%20-%20I...   
...           ...                                                ...   
31377         117  http://he3.magnatune.com/all/56-La%20Bressanin...   
31378          29  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31379          59  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31380          88  http://he3.magnatune.com/all/57-Lost%20is%20my...   
31381          29  http://he3.magnatune.com/all/58-A%20Toy%20for%...   

                                                mp3_path  
0      f/american_bach_soloists-j_s__bach_solo_cantat...  
1      f/american_bach_soloists-j_s__bach_solo_cantat...  
2      f/american_bach_soloists-j_s__bach_solo_cantat...  
3      f/american_bach_soloists-j_s__bach_solo_cantat...  
4      f/american_bach_soloists-j_s__bach_solo_cantat...  
...                                                  ...  
31377  8/jacob_heringman-blame_not_my_lute-56-la_bres...  
31378  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31379  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31380  8/jacob_heringman-blame_not_my_lute-57-lost_is...  
31381  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...  

[31382 rows x 10 columns]

# 50 tags with the largest quantity in dataset

In [4]:
tags = adnotations.filter(regex='[^(clip_id|mp3_path)]').sum().nlargest(50).keys().to_numpy('str')
tags

array(['guitar', 'classical', 'slow', 'techno', 'strings', 'drums',
       'electronic', 'rock', 'fast', 'piano', 'ambient', 'beat', 'violin',
       'vocal', 'synth', 'female', 'indian', 'opera', 'male', 'singing',
       'vocals', 'no vocals', 'harpsichord', 'loud', 'quiet', 'flute',
       'woman', 'male vocal', 'no vocal', 'pop', 'soft', 'sitar', 'solo',
       'man', 'classic', 'choir', 'voice', 'new age', 'dance',
       'male voice', 'female vocal', 'beats', 'harp', 'cello', 'no voice',
       'weird', 'country', 'female voice', 'metal', 'choral'],
      dtype='<U12')

# Binary tags

In [5]:
binary = adnotations[tags]
binary

guitar  classical  slow  techno  strings  drums  electronic  rock  \
0           0          1     0       0        1      0           0     0   
1           0          1     0       0        1      0           0     0   
2           0          1     0       0        0      0           0     0   
3           0          0     0       0        0      0           0     0   
4           0          1     0       0        1      0           0     0   
...       ...        ...   ...     ...      ...    ...         ...   ...   
25858       1          0     0       0        0      0           0     0   
25859       1          0     1       0        1      0           0     0   
25860       1          1     1       0        1      0           0     0   
25861       1          1     1       0        0      0           0     0   
25862       1          1     1       0        0      0           0     0   

       fast  piano  ...  female vocal  beats  harp  cello  no voice  weird  \
0         0      0  ...             0      0     0      0         0      0   
1         0      0  ...             0      0     0      0         0      0   
2         0      0  ...             0      0     0      0         0      0   
3         0      0  ...             0      0     0      0         0      0   
4         0      0  ...             0      0     0      0         0      0   
...     ...    ...  ...           ...    ...   ...    ...       ...    ...   
25858     0      0  ...             0      0     0      0         0      0   
25859     0      0  ...             0      0     1      0         0      0   
25860     0      0  ...             0      0     0      0         0      0   
25861     0      0  ...             0      0     0      0         0      0   
25862     0      0  ...             0      0     0      0         0      0   

       country  female voice  metal  choral  
0            0             0      0       0  
1            0             0      0       0  
2            0             0      0       0  
3            0             0      0       0  
4            0             0      0       0  
...        ...           ...    ...     ...  
25858        0             0      0       0  
25859        0             0      0       0  
25860        0             0      0       0  
25861        0             0      0       0  
25862        0             0      0       0  

[25863 rows x 50 columns]

In [6]:
binary_np = binary.to_numpy()
print(binary_np.shape)
binary_np

(25863, 50)


array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

# Spliting dataset to train, valid and test datasets

In [7]:
dataset = pd.DataFrame(adnotations.mp3_path, columns=['idx', 'mp3_path'])
dataset["idx"] = dataset.index
dataset

idx                                           mp3_path
0          0  f/american_bach_soloists-j_s__bach_solo_cantat...
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
2          2  f/american_bach_soloists-j_s__bach_solo_cantat...
3          3  f/american_bach_soloists-j_s__bach_solo_cantat...
4          4  f/american_bach_soloists-j_s__bach_solo_cantat...
...      ...                                                ...
25858  25858  8/jacob_heringman-blame_not_my_lute-56-la_bres...
25859  25859  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25860  25860  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25861  25861  8/jacob_heringman-blame_not_my_lute-57-lost_is...
25862  25862  8/jacob_heringman-blame_not_my_lute-58-a_toy_f...

[25863 rows x 2 columns]

In [8]:
dataset.to_numpy()

array([[0,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-30-59.mp3'],
       [1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [2,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-262-291.mp3'],
       ...,
       [25860,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-30-59.mp3'],
       [25861,
        '8/jacob_heringman-blame_not_my_lute-57-lost_is_my_lyberty-59-88.mp3'],
       [25862,
        '8/jacob_heringman-blame_not_my_lute-58-a_toy_for_monica_bishop-0-29.mp3']],
      dtype=object)

In [ ]:
train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

In [9]:
## Train

In [39]:
train = dataset.sample(round(train_ratio*len(dataset.index)),random_state=10)
train

idx                                           mp3_path group
14372  14372  c/domased-new_memories-07-first_sun_rays-233-2...     c
10497  10497  8/tim_rayborn-veils_of_light-05-kashik-204-233...     8
19701  19701  7/falik-elvolution-10-mediterranean_blue-262-2...     7
19967  19967  4/falling_you-touch-10-reading_the_leaves_by_m...     4
15989  15989              5/rapoon-cidar-08-cimbala-436-465.mp3     5
...      ...                                                ...   ...
4665    4665  1/vito_paternoster-cd1bach_cello_suites-02-sui...     1
15801  15801  6/norine_braun-crow-08-another_mans_fate-59-88...     6
18557  18557  c/glen_bledsoe-up_and_down-09-rumination-175-2...     c
1903    1903  e/dac_crowell-within_this_space-01-running_dep...     e
10336  10336  5/domased-selection-05-highway_accident-175-20...     5

[20690 rows x 3 columns]

In [40]:
dataset_train = train.to_numpy()
np.save(open('../split/mtat/train.npy', 'wb'), dataset_train)
dataset_train

array([[14372, 'c/domased-new_memories-07-first_sun_rays-233-262.mp3',
        'c'],
       [10497, '8/tim_rayborn-veils_of_light-05-kashik-204-233.mp3', '8'],
       [19701, '7/falik-elvolution-10-mediterranean_blue-262-291.mp3',
        '7'],
       ...,
       [18557, 'c/glen_bledsoe-up_and_down-09-rumination-175-204.mp3',
        'c'],
       [1903,
        'e/dac_crowell-within_this_space-01-running_depth-581-610.mp3',
        'e'],
       [10336, '5/domased-selection-05-highway_accident-175-204.mp3',
        '5']], dtype=object)

In [41]:
mini_train = train.sample(len(train.index) // 10,random_state=10)
mini_train

idx                                           mp3_path group
3589    3589       5/rapoon-fallen_gods-02-iron_path-88-117.mp3     5
24734  24734     3/jag-four_strings-18-riverside_rag-88-117.mp3     3
21840  21840  6/ed_martin-luis_milan__el_maestro-12-fantasia...     6
414      414  6/gerard_satamian-dry_fig_trees-01-chansons_sa...     6
14903  14903  5/dj_markitos-unreachable_destiny-07-open_your...     5
...      ...                                                ...   ...
22972  22972    9/the_wretch-ambulatory-13-specimen-204-233.mp3     9
25492  25492  e/magnatune_compilation-high_energy_rock_and_r...     e
771      771         3/sherefe-opium-01-gole_sangam-175-204.mp3     3
8433    8433            6/drop_trio-cezanne-04-luna-291-320.mp3     6
17847  17847  9/ya_elah-each_of_us-09-el_na_refa_na_la-30-59...     9

[2069 rows x 3 columns]

In [44]:
dataset_mini_train = train.to_numpy()
np.save(open('../split/mtat-mini/train.npy', 'wb'), dataset_mini_train)
dataset_mini_train

array([[14372, 'c/domased-new_memories-07-first_sun_rays-233-262.mp3',
        'c'],
       [10497, '8/tim_rayborn-veils_of_light-05-kashik-204-233.mp3', '8'],
       [19701, '7/falik-elvolution-10-mediterranean_blue-262-291.mp3',
        '7'],
       ...,
       [18557, 'c/glen_bledsoe-up_and_down-09-rumination-175-204.mp3',
        'c'],
       [1903,
        'e/dac_crowell-within_this_space-01-running_depth-581-610.mp3',
        'e'],
       [10336, '5/domased-selection-05-highway_accident-175-204.mp3',
        '5']], dtype=object)

In [12]:
## Valid

In [45]:
valid = dataset.drop(train.index)
valid = valid.sample(round(valid_ratio*len(dataset.index)),random_state=10)
valid

idx                                           mp3_path group
12918  12918       7/solace-shawaza-06-ophelias_hands-30-59.mp3     7
23889  23889  0/american_bach_soloists-j_s__bach__transcript...     0
7291    7291       8/ivilion-terean-03-urtulitreator-88-117.mp3     8
19367  19367  3/jacob_heringman-siena_lute_book-10-fantasia_...     3
12868  12868  f/kyiv_chamber_choir-masterpieces_of_the_ukrai...     f
...      ...                                                ...   ...
22672  22672  2/maryse_carlin-rameau__pieces_de_clavecin_en_...     2
22619  22619  3/panacea-songs_and_dance_music_of_europe_east...     3
2972    2972  2/indidginus-seismic-02-catatonic_convertor-59...     2
21794  21794  3/c__layne-potemkin_villages-12-down_at_the_bo...     3
10722  10722  0/the_bots-truth-05-never_fall_in_love-146-175...     0

[2586 rows x 3 columns]

In [46]:
dataset_valid = valid.to_numpy()
np.save(open('../split/mtat/valid.npy', 'wb'), dataset_valid)
dataset_valid

array([[12918, '7/solace-shawaza-06-ophelias_hands-30-59.mp3', '7'],
       [23889,
        '0/american_bach_soloists-j_s__bach__transcriptions_of_italian_music-15-psalm_51_tilge_hochster_meine_sunden_xii_largo_verses_17_and_18-88-117.mp3',
        '0'],
       [7291, '8/ivilion-terean-03-urtulitreator-88-117.mp3', '8'],
       ...,
       [2972, '2/indidginus-seismic-02-catatonic_convertor-59-88.mp3',
        '2'],
       [21794,
        '3/c__layne-potemkin_villages-12-down_at_the_bottom-204-233.mp3',
        '3'],
       [10722, '0/the_bots-truth-05-never_fall_in_love-146-175.mp3', '0']],
      dtype=object)

In [47]:
mini_valid = valid.sample(len(valid.index) // 10,random_state=10)
mini_valid

idx                                           mp3_path group
23216  23216  f/jacob_heringman_and_catherine_king-luis_mila...     f
12415  12415  d/shira_kammen-mistral-06-he_tres_doulz_rossig...     d
15445  15445  b/paul_beier-alessandro_piccinini-07-toccata_x...     b
5961    5961  b/dj_cary-power_synths-03-from_love_2_wicked_a...     b
24875  24875  3/jag-four_strings-19-helena_street_corner_blu...     3
...      ...                                                ...   ...
6062    6062        7/aba_structure-epic-03-houseboats-0-29.mp3     7
2845    2845  2/zephyrus-angelus-02-ave_maria___virgo_serena...     2
1095    1095  5/thursday_group-uncle_mean-01-like_white_on_r...     5
19740  19740  d/the_west_exit-nocturne-10-nine_lives-146-175...     d
15673  15673  f/american_bach_soloists-j_s__bach_solo_cantat...     f

[258 rows x 3 columns]

In [48]:
dataset_mini_valid = mini_valid.to_numpy()
np.save(open('../split/mtat-mini/valid.npy', 'wb'), dataset_mini_valid)
dataset_mini_valid

array([[23216,
        'f/jacob_heringman_and_catherine_king-luis_milan_el_maestro-14-fantasia_26-88-117.mp3',
        'f'],
       [12415,
        'd/shira_kammen-mistral-06-he_tres_doulz_rossignolbreton_gavottes-88-117.mp3',
        'd'],
       [15445,
        'b/paul_beier-alessandro_piccinini-07-toccata_xvii-59-88.mp3',
        'b'],
       [5961,
        'b/dj_cary-power_synths-03-from_love_2_wicked_allstars-175-204.mp3',
        'b'],
       [24875,
        '3/jag-four_strings-19-helena_street_corner_blues-59-88.mp3',
        '3'],
       [1828,
        'c/atomic_opera-alpha_and_oranges-01-rain_parade-146-175.mp3',
        'c'],
       [25480,
        'c/edward_martin-art_of_the_lute_in_renaissance_france-24-peysen_ende_trueren_phalese-59-88.mp3',
        'c'],
       [2073,
        '4/seth_carlin-schubert__works_for_solo_fortepiano-01-sonata_in_eflat_major_opus_posth__122__allegro_moderato-175-204.mp3',
        '4'],
       [20394, '6/norine_braun-crow-10-wingsphoenix-175-204.m

In [21]:
test = dataset.drop(train.index)
test = test.drop(valid.index)
test

idx                                           mp3_path
1          1  f/american_bach_soloists-j_s__bach_solo_cantat...
11        11  e/steven_devine-portrait_of_an_english_harpsic...
18        18  9/american_bach_soloists-heinrich_schutz__musi...
26        26  9/american_bach_soloists-heinrich_schutz__musi...
33        33  9/american_bach_soloists-heinrich_schutz__musi...
...      ...                                                ...
25769  25769  b/janine_johnson-bach_goldberg_variations-29-v...
25810  25810  b/janine_johnson-bach_goldberg_variations-31-v...
25833  25833  3/musica_franca-boismortier__sonatas_for_two_b...
25836  25836  3/musica_franca-boismortier__sonatas_for_two_b...
25851  25851  7/magnaloops-world_loops_2-54-osdmichaelmasley...

[2587 rows x 2 columns]

In [49]:
dataset_test = test.to_numpy()
np.save(open('../split/mtat/test.npy', 'wb'), dataset_test)
dataset_test

array([[1,
        'f/american_bach_soloists-j_s__bach_solo_cantatas-01-bwv54__i_aria-146-175.mp3'],
       [11,
        'e/steven_devine-portrait_of_an_english_harpsichord-01-lesson_1_in_g_major_prelude_james_nares-0-29.mp3'],
       [18,
        '9/american_bach_soloists-heinrich_schutz__musicalische_exequien-01-musicalische_exequien_swv_279_teil_i_concert_in_form_einer_teutschen_begrabnismissa-146-175.mp3'],
       ...,
       [25833,
        '3/musica_franca-boismortier__sonatas_for_two_bassoons_and_continuo-37-rondeau_in_a_minor_op__40-88-117.mp3'],
       [25836,
        '3/musica_franca-boismortier__sonatas_for_two_bassoons_and_continuo-38-chaconne_in_a_major_op__66-59-88.mp3'],
       [25851,
        '7/magnaloops-world_loops_2-54-osdmichaelmasley644-0-29.mp3']],
      dtype=object)

In [50]:
mini_test = test.sample(len(test.index) // 10,random_state=10)
mini_test

idx                                           mp3_path
6392    6392  b/magnatune_compilation-world_fusion-03-michae...
16553  16553            e/solace-balance-08-miss_anime-0-29.mp3
23898  23898  2/jesse_manno-sea_spirits-15-receiving_the_gif...
10798  10798  2/indidginus-as_above_so_below-05-omega_3-204-...
23881  23881  3/jan_hanford-24_preludes_for_solo_piano-15-pr...
...      ...                                                ...
7601    7601  b/lisa_debenedictis-mixter_one-04-belowdufirst...
2297    2297    2/indidginus-seismic-01-superstring-378-407.mp3
2009    2009  5/kammen___swan-wild_wood-01-shetland_set-59-8...
5667    5667  5/john_fleagle-worlds_bliss__medieval_songs_of...
14560  14560  1/william_brooks-karma_dogs-07-isabel-146-175.mp3

[258 rows x 2 columns]

In [51]:
dataset_mini_test = mini_test.to_numpy()
np.save(open('../split/mtat-mini/test.npy', 'wb'), dataset_mini_test)
dataset_mini_test

array([[6392,
        'b/magnatune_compilation-world_fusion-03-michael_masley_kubricks_tube-0-29.mp3'],
       [16553, 'e/solace-balance-08-miss_anime-0-29.mp3'],
       [23898,
        '2/jesse_manno-sea_spirits-15-receiving_the_gift-204-233.mp3'],
       [10798, '2/indidginus-as_above_so_below-05-omega_3-204-233.mp3'],
       [23881,
        '3/jan_hanford-24_preludes_for_solo_piano-15-prelude_no__15_in_a_minor-30-59.mp3'],
       [21026, '2/saros-soundscapes-11-natures_grace-349-378.mp3'],
       [19357, '2/jamie_janover-evolutions-10-evolutions-291-320.mp3'],
       [6109,
        '6/farallon_recorder_quartet-ludwig_senfl-03-ich_weiss_nit_was_er_ihr_verbiess-0-29.mp3'],
       [3698, '4/human_response-delirious-02-landlocked-117-146.mp3'],
       [24011,
        'f/the_napoleon_blown_aparts-thrill_hype-15-thrill_bound-175-204.mp3'],
       [3753, 'a/kitka-nectar-02-malo_selo_bulgaria-59-88.mp3'],
       [16009,
        'f/american_baroque-the_four_seasons_by_vivaldi-08-concerto_no_