In [1]:
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics

from components.common import Config
from components.predictor import Predictor, SklearnPredictor
from external.musicnn import Musicnn

config = Config(model=KNeighborsClassifier(),
                model_filename_path = "../models",
                data_path='../data',
                dataset_split_path= "../split",
                dataset_name="mtat-20")
predictor = SklearnPredictor(config, model_filename="mtat-20/model.bin")

In [2]:
import numpy as np

test_files = np.load("../split/mtat-20/test.npy", allow_pickle=True)
test_files

array([[13782, '2/indidginus-seismic-03-master_of_masters-349-378.mp3'],
       [31415,
        '7/american_bach_soloists-j_s__bach__mass_in_b_minor_cd2-07-et_in_spiritum_sanctum_dominum-262-291.mp3'],
       [5814,
        '0/jeffrey_luck_lucas-what_we_whisper-01-you_knew_it_well-175-204.mp3'],
       ...,
       [47511, '0/apa_ya-apa_ya-12-african_wedding_song-146-175.mp3'],
       [35566,
        'f/kenji_williams-faces_of_epiphany-08-free_energy-88-117.mp3'],
       [30965, '3/jag-four_strings-07-country_romp-30-59.mp3']],
      dtype=object)

In [3]:
binary = {row[0]: row[1:] for row in np.load("../split/mtat-20/binary.npy", allow_pickle=True)}
binary

{2: array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
 6: array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
 10: array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 11: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 12: array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 14: array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 21: array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 23: array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 29: array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 32: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 33: array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 37: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 38: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 39: array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0

In [4]:
import os
file = test_files[2][1]
file = os.path.join("../data/mtat/emb/0/american_bach_soloists-j_s__bach__cantatas_volume_v-01-gleichwie_der_regen_und_schnee_vom_himmel_fallt_bwv_18_i_sinfonia-117-146.npy")
predictor.predict_data(np.load(file, allow_pickle=True))

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
result = predictor.predict_data_prob(np.load(file, allow_pickle=True))
result

array([[0. , 0.8, 0.2, 0. , 0.4, 0. , 0. , 0. , 0. , 0.2, 0.2, 0. , 0.4,
        0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [29]:
import pandas as pd

out = predictor.predict_tags_prob("../data/mtat/mp3/0/american_bach_soloists-j_s__bach__cantatas_volume_v-01-gleichwie_der_regen_und_schnee_vom_himmel_fallt_bwv_18_i_sinfonia-117-146.mp3").T
out

/home/robak/.virtualenvs/labelthissongforme/lib/python3.10/site-packages/torchopenl3/models.py:200: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = librosa.filters.mel(


classical  violin  strings  ambient  slow  piano  male  opera  indian  \
0        0.8     0.4      0.4      0.2   0.2    0.2   0.0    0.0     0.0   

   female  synth  vocal  guitar  beat  fast  rock  electronic  drums  techno  \
0     0.0    0.0    0.0     0.0   0.0   0.0   0.0         0.0    0.0     0.0   

   singing  
0      0.0

In [32]:
out.shape[0]>1

True